unit blocks_mct;

interface

//todo: peremestit' suda mnozhestva prozrachnih i t.d. blokov

uses types_mct;

var blocks_id:TBlock_set_ar;
blocks_change_id:TBlock_change_ar;

trans_bl:set_trans_blocks;
light_bl:set_trans_blocks;
diff_bl:set_trans_blocks;
solid_bl:set_trans_blocks;

light_ar:TID_data_ar;
diffuse_ar:TID_data_ar;

procedure fill_standard_blocks(blocks_id:pTBlock_set_ar);
procedure fill_sets;

implementation

procedure fill_sets;
var i,j:integer;
begin
  trans_bl:=[];
  light_bl:=[];
  diff_bl:=[];
  solid_bl:=[];

  setlength(light_ar,0);
  setlength(diffuse_ar,0);

  for i:=0 to length(blocks_id)-1 do
  begin
    if blocks_id[i].transparent then include(trans_bl,i);
    if blocks_id[i].light_level>0 then
    begin
      include(light_bl,i);
      j:=length(light_ar);
      setlength(light_ar,j+1);
      light_ar[j].id:=i;
      light_ar[j].data:=blocks_id[i].light_level;
    end;
    if blocks_id[i].diffuse then
    begin
      include(diff_bl,i);
      j:=length(diffuse_ar);
      setlength(diffuse_ar,j+1);
      diffuse_ar[j].id:=i;
      diffuse_ar[j].data:=blocks_id[i].diffuse_level;
    end;
    if blocks_id[i].solid then include(solid_bl,i);
  end;
end;

procedure fill_standard_blocks(blocks_id:pTBlock_set_ar);
begin
  setlength(blocks_id^,125);

  //todo: proverit' vse data_value

  blocks_id^[0].id:=0;
  blocks_id^[0].name:='Air';
  blocks_id^[0].solid:=false;
  blocks_id^[0].transparent:=true;
  blocks_id^[0].diffuse:=false;
  blocks_id^[0].light_level:=0;
  blocks_id^[0].diffuse_level:=0;
  blocks_id^[0].tile:=false;
  setlength(blocks_id^[0].data,0);

  blocks_id^[1].id:=1;
  blocks_id^[1].name:='Stone';
  blocks_id^[1].solid:=true;
  blocks_id^[1].transparent:=false;
  blocks_id^[1].diffuse:=false;
  blocks_id^[1].light_level:=0;
  blocks_id^[1].diffuse_level:=0;
  blocks_id^[1].tile:=false;
  setlength(blocks_id^[1].data,0);

  blocks_id^[2].id:=2;
  blocks_id^[2].name:='Grass';
  blocks_id^[2].solid:=true;
  blocks_id^[2].transparent:=false;
  blocks_id^[2].diffuse:=false;
  blocks_id^[2].light_level:=0;
  blocks_id^[2].diffuse_level:=0;
  blocks_id^[2].tile:=false;
  setlength(blocks_id^[2].data,0);

  blocks_id^[3].id:=3;
  blocks_id^[3].name:='Dirt';
  blocks_id^[3].solid:=true;
  blocks_id^[3].transparent:=false;
  blocks_id^[3].diffuse:=false;
  blocks_id^[3].light_level:=0;
  blocks_id^[3].diffuse_level:=0;
  blocks_id^[3].tile:=false;
  setlength(blocks_id^[3].data,0);

  blocks_id^[4].id:=4;
  blocks_id^[4].name:='Cobblestone';
  blocks_id^[4].solid:=true;
  blocks_id^[4].transparent:=false;
  blocks_id^[4].diffuse:=false;
  blocks_id^[4].light_level:=0;
  blocks_id^[4].diffuse_level:=0;
  blocks_id^[4].tile:=false;
  setlength(blocks_id^[4].data,0);

  blocks_id^[5].id:=5;
  blocks_id^[5].name:='Wooden plank';
  blocks_id^[5].solid:=true;
  blocks_id^[5].transparent:=false;
  blocks_id^[5].diffuse:=false;
  blocks_id^[5].light_level:=0;
  blocks_id^[5].diffuse_level:=0;
  blocks_id^[5].tile:=false;
  setlength(blocks_id^[5].data,4);
  blocks_id^[5].data[0].data_id:=0;
  blocks_id^[5].data[0].data_name:='Oak Wood Planks';
  blocks_id^[5].data[1].data_id:=1;
  blocks_id^[5].data[1].data_name:='Spruce Wood Planks';
  blocks_id^[5].data[2].data_id:=2;
  blocks_id^[5].data[2].data_name:='Birch Wood Planks';
  blocks_id^[5].data[3].data_id:=3;
  blocks_id^[5].data[3].data_name:='Jungle Wood Planks';

  blocks_id^[6].id:=6;
  blocks_id^[6].name:='Sapling';
  blocks_id^[6].solid:=false;
  blocks_id^[6].transparent:=true;
  blocks_id^[6].diffuse:=false;
  blocks_id^[6].light_level:=0;
  blocks_id^[6].diffuse_level:=0;
  blocks_id^[6].tile:=false;
  setlength(blocks_id^[6].data,4);
  blocks_id^[6].data[0].data_id:=0;
  blocks_id^[6].data[0].data_name:='Oak Sapling';
  blocks_id^[6].data[1].data_id:=1;
  blocks_id^[6].data[1].data_name:='Spruce Sapling';
  blocks_id^[6].data[2].data_id:=2;
  blocks_id^[6].data[2].data_name:='Birch Sapling';
  blocks_id^[6].data[3].data_id:=3;
  blocks_id^[6].data[3].data_name:='Jungle Tree Sapling';

  blocks_id^[7].id:=7;
  blocks_id^[7].name:='Bedrock';
  blocks_id^[7].solid:=true;
  blocks_id^[7].transparent:=false;
  blocks_id^[7].diffuse:=false;
  blocks_id^[7].light_level:=0;
  blocks_id^[7].diffuse_level:=0;
  blocks_id^[7].tile:=false;
  setlength(blocks_id^[7].data,0);

  blocks_id^[8].id:=8;
  blocks_id^[8].name:='Water';
  blocks_id^[8].solid:=false;
  blocks_id^[8].transparent:=true;
  blocks_id^[8].diffuse:=true;
  blocks_id^[8].light_level:=0;
  blocks_id^[8].diffuse_level:=2;
  blocks_id^[8].tile:=false;
  setlength(blocks_id^[8].data,9);
  blocks_id^[8].data[0].data_id:=0;
  blocks_id^[8].data[0].data_name:='Full block';
  blocks_id^[8].data[1].data_id:=1;
  blocks_id^[8].data[1].data_name:='7/8 of block';
  blocks_id^[8].data[2].data_id:=2;
  blocks_id^[8].data[2].data_name:='6/8 of block';
  blocks_id^[8].data[3].data_id:=3;
  blocks_id^[8].data[3].data_name:='5/8 of block';
  blocks_id^[8].data[4].data_id:=4;
  blocks_id^[8].data[4].data_name:='4/8 of block';
  blocks_id^[8].data[5].data_id:=5;
  blocks_id^[8].data[5].data_name:='3/8 of block';
  blocks_id^[8].data[6].data_id:=6;
  blocks_id^[8].data[6].data_name:='2/8 of block';
  blocks_id^[8].data[7].data_id:=7;
  blocks_id^[8].data[7].data_name:='1/8 of block';
  blocks_id^[8].data[8].data_id:=8;
  blocks_id^[8].data[8].data_name:='Full block flowing down';

  blocks_id^[9].id:=9;
  blocks_id^[9].name:='Stationary water';
  blocks_id^[9].solid:=false;
  blocks_id^[9].transparent:=true;
  blocks_id^[9].diffuse:=true;
  blocks_id^[9].light_level:=0;
  blocks_id^[9].diffuse_level:=2;
  blocks_id^[9].tile:=false;
  setlength(blocks_id^[9].data,2);
  blocks_id^[9].data[0].data_id:=0;
  blocks_id^[9].data[0].data_name:='Full still block';
  blocks_id^[9].data[1].data_id:=8;
  blocks_id^[9].data[1].data_name:='Full still block flowing down';

  blocks_id^[10].id:=10;
  blocks_id^[10].name:='Lava';
  blocks_id^[10].solid:=false;
  blocks_id^[10].transparent:=false;
  blocks_id^[10].diffuse:=false;
  blocks_id^[10].light_level:=15;
  blocks_id^[10].diffuse_level:=0;
  blocks_id^[10].tile:=false;
  setlength(blocks_id^[10].data,5);
  blocks_id^[10].data[0].data_id:=0;
  blocks_id^[10].data[0].data_name:='Full block';
  blocks_id^[10].data[1].data_id:=2;
  blocks_id^[10].data[1].data_name:='6/8 of block';
  blocks_id^[10].data[2].data_id:=4;
  blocks_id^[10].data[2].data_name:='4/8 of block';
  blocks_id^[10].data[3].data_id:=6;
  blocks_id^[10].data[3].data_name:='1/8 of block';
  blocks_id^[10].data[4].data_id:=8;
  blocks_id^[10].data[4].data_name:='Full block flowing down';

  blocks_id^[11].id:=11;
  blocks_id^[11].name:='Stationary lava';
  blocks_id^[11].solid:=false;
  blocks_id^[11].transparent:=false;
  blocks_id^[11].diffuse:=false;
  blocks_id^[11].light_level:=15;
  blocks_id^[11].diffuse_level:=0;
  blocks_id^[11].tile:=false;
  setlength(blocks_id^[11].data,5);
  blocks_id^[11].data[0].data_id:=0;
  blocks_id^[11].data[0].data_name:='Full block';
  blocks_id^[11].data[1].data_id:=2;
  blocks_id^[11].data[1].data_name:='6/8 of block';
  blocks_id^[11].data[2].data_id:=4;
  blocks_id^[11].data[2].data_name:='4/8 of block';
  blocks_id^[11].data[3].data_id:=6;
  blocks_id^[11].data[3].data_name:='1/8 of block';
  blocks_id^[11].data[4].data_id:=8;
  blocks_id^[11].data[4].data_name:='Full block flowing down';

  blocks_id^[12].id:=12;
  blocks_id^[12].name:='Sand';
  blocks_id^[12].solid:=true;
  blocks_id^[12].transparent:=false;
  blocks_id^[12].diffuse:=false;
  blocks_id^[12].light_level:=0;
  blocks_id^[12].diffuse_level:=0;
  blocks_id^[12].tile:=false;
  setlength(blocks_id^[12].data,0);

  blocks_id^[13].id:=13;
  blocks_id^[13].name:='Gravel';
  blocks_id^[13].solid:=true;
  blocks_id^[13].transparent:=false;
  blocks_id^[13].diffuse:=false;
  blocks_id^[13].light_level:=0;
  blocks_id^[13].diffuse_level:=0;
  blocks_id^[13].tile:=false;
  setlength(blocks_id^[13].data,0);

  blocks_id^[14].id:=14;
  blocks_id^[14].name:='Gold Ore';
  blocks_id^[14].solid:=true;
  blocks_id^[14].transparent:=false;
  blocks_id^[14].diffuse:=false;
  blocks_id^[14].light_level:=0;
  blocks_id^[14].diffuse_level:=0;
  blocks_id^[14].tile:=false;
  setlength(blocks_id^[14].data,0);

  blocks_id^[15].id:=15;
  blocks_id^[15].name:='Iron Ore';
  blocks_id^[15].solid:=true;
  blocks_id^[15].transparent:=false;
  blocks_id^[15].diffuse:=false;
  blocks_id^[15].light_level:=0;
  blocks_id^[15].diffuse_level:=0;
  blocks_id^[15].tile:=false;
  setlength(blocks_id^[15].data,0);

  blocks_id^[16].id:=16;
  blocks_id^[16].name:='Coal Ore';
  blocks_id^[16].solid:=true;
  blocks_id^[16].transparent:=false;
  blocks_id^[16].diffuse:=false;
  blocks_id^[16].light_level:=0;
  blocks_id^[16].diffuse_level:=0;
  blocks_id^[16].tile:=false;
  setlength(blocks_id^[16].data,0);

  blocks_id^[17].id:=17;
  blocks_id^[17].name:='Wood';
  blocks_id^[17].solid:=true;
  blocks_id^[17].transparent:=false;
  blocks_id^[17].diffuse:=false;
  blocks_id^[17].light_level:=0;
  blocks_id^[17].diffuse_level:=0;
  blocks_id^[17].tile:=false;
  setlength(blocks_id^[17].data,4);
  blocks_id^[17].data[0].data_id:=0;
  blocks_id^[17].data[0].data_name:='Oak Wood';
  blocks_id^[17].data[1].data_id:=1;
  blocks_id^[17].data[1].data_name:='Pine/Spruce Wood';
  blocks_id^[17].data[2].data_id:=2;
  blocks_id^[17].data[2].data_name:='Birch Wood';
  blocks_id^[17].data[3].data_id:=3;
  blocks_id^[17].data[3].data_name:='Jungle Wood';

  blocks_id^[18].id:=18;
  blocks_id^[18].name:='Leaves';
  blocks_id^[18].solid:=true;
  blocks_id^[18].transparent:=true;
  blocks_id^[18].diffuse:=true;
  blocks_id^[18].light_level:=0;
  blocks_id^[18].diffuse_level:=0;
  blocks_id^[18].tile:=false;
  setlength(blocks_id^[18].data,4);
  blocks_id^[18].data[0].data_id:=0;
  blocks_id^[18].data[0].data_name:='Oak Leaves';
  blocks_id^[18].data[1].data_id:=1;
  blocks_id^[18].data[1].data_name:='Pine/Spruce Leaves';
  blocks_id^[18].data[2].data_id:=2;
  blocks_id^[18].data[2].data_name:='Birch Leaves';
  blocks_id^[18].data[3].data_id:=3;
  blocks_id^[18].data[3].data_name:='Jungle Leaves';

  blocks_id^[19].id:=19;
  blocks_id^[19].name:='Sponge';
  blocks_id^[19].solid:=true;
  blocks_id^[19].transparent:=false;
  blocks_id^[19].diffuse:=false;
  blocks_id^[19].light_level:=0;
  blocks_id^[19].diffuse_level:=0;
  blocks_id^[19].tile:=false;
  setlength(blocks_id^[19].data,0);

  blocks_id^[20].id:=20;
  blocks_id^[20].name:='Glass';
  blocks_id^[20].solid:=true;
  blocks_id^[20].transparent:=true;
  blocks_id^[20].diffuse:=false;
  blocks_id^[20].light_level:=0;
  blocks_id^[20].diffuse_level:=0;
  blocks_id^[20].tile:=false;
  setlength(blocks_id^[20].data,0);

  blocks_id^[21].id:=21;
  blocks_id^[21].name:='Lapis Lazuli Ore';
  blocks_id^[21].solid:=true;
  blocks_id^[21].transparent:=false;
  blocks_id^[21].diffuse:=false;
  blocks_id^[21].light_level:=0;
  blocks_id^[21].diffuse_level:=0;
  blocks_id^[21].tile:=false;
  setlength(blocks_id^[21].data,0);

  blocks_id^[22].id:=22;
  blocks_id^[22].name:='Lapis Lazuli Block';
  blocks_id^[22].solid:=true;
  blocks_id^[22].transparent:=false;
  blocks_id^[22].diffuse:=false;
  blocks_id^[22].light_level:=0;
  blocks_id^[22].diffuse_level:=0;
  blocks_id^[22].tile:=false;
  setlength(blocks_id^[22].data,0);

  blocks_id^[23].id:=23;
  blocks_id^[23].name:='Dispenser';
  blocks_id^[23].solid:=true;
  blocks_id^[23].transparent:=false;
  blocks_id^[23].diffuse:=false;
  blocks_id^[23].light_level:=0;
  blocks_id^[23].diffuse_level:=0;
  blocks_id^[23].tile:=true;
  setlength(blocks_id^[23].data,4);
  blocks_id^[23].data[0].data_id:=2;
  blocks_id^[23].data[0].data_name:='Facing north';
  blocks_id^[23].data[1].data_id:=3;
  blocks_id^[23].data[1].data_name:='Facing south';
  blocks_id^[23].data[2].data_id:=4;
  blocks_id^[23].data[2].data_name:='Facing west';
  blocks_id^[23].data[3].data_id:=5;
  blocks_id^[23].data[3].data_name:='Facing east';

  blocks_id^[24].id:=24;
  blocks_id^[24].name:='Sandstone';
  blocks_id^[24].solid:=true;
  blocks_id^[24].transparent:=false;
  blocks_id^[24].diffuse:=false;
  blocks_id^[24].light_level:=0;
  blocks_id^[24].diffuse_level:=0;
  blocks_id^[24].tile:=false;
  setlength(blocks_id^[24].data,3);
  blocks_id^[24].data[0].data_id:=0;
  blocks_id^[24].data[0].data_name:='Normal';
  blocks_id^[24].data[1].data_id:=1;
  blocks_id^[24].data[1].data_name:='Hieroglyphic/Creeper';
  blocks_id^[24].data[2].data_id:=2;
  blocks_id^[24].data[2].data_name:='Smooth';

  blocks_id^[25].id:=25;
  blocks_id^[25].name:='Note Block';
  blocks_id^[25].solid:=true;
  blocks_id^[25].transparent:=false;
  blocks_id^[25].diffuse:=false;
  blocks_id^[25].light_level:=0;
  blocks_id^[25].diffuse_level:=0;
  blocks_id^[25].tile:=true;
  setlength(blocks_id^[25].data,0);

  blocks_id^[26].id:=26;
  blocks_id^[26].name:='Bed';
  blocks_id^[26].solid:=false;
  blocks_id^[26].transparent:=true;
  blocks_id^[26].diffuse:=false;
  blocks_id^[26].light_level:=0;
  blocks_id^[26].diffuse_level:=0;
  blocks_id^[26].tile:=false;
  setlength(blocks_id^[26].data,8);
  blocks_id^[26].data[0].data_id:=0;
  blocks_id^[26].data[0].data_name:='Head pointing South (foot)';
  blocks_id^[26].data[1].data_id:=1;
  blocks_id^[26].data[1].data_name:='Head pointing West (foot)';
  blocks_id^[26].data[2].data_id:=2;
  blocks_id^[26].data[2].data_name:='Head pointing North (foot)';
  blocks_id^[26].data[3].data_id:=3;
  blocks_id^[26].data[3].data_name:='Head pointing East (foot)';
  blocks_id^[26].data[4].data_id:=8;
  blocks_id^[26].data[4].data_name:='Head pointing South (head)';
  blocks_id^[26].data[5].data_id:=9;
  blocks_id^[26].data[5].data_name:='Head pointing West (head)';
  blocks_id^[26].data[6].data_id:=10;
  blocks_id^[26].data[6].data_name:='Head pointing North (head)';
  blocks_id^[26].data[7].data_id:=11;
  blocks_id^[26].data[7].data_name:='Head pointing East (head)';

  blocks_id^[27].id:=27;
  blocks_id^[27].name:='Powered Rail';
  blocks_id^[27].solid:=false;
  blocks_id^[27].transparent:=true;
  blocks_id^[27].diffuse:=false;
  blocks_id^[27].light_level:=0;
  blocks_id^[27].diffuse_level:=0;
  blocks_id^[27].tile:=false;
  setlength(blocks_id^[27].data,12);
  blocks_id^[27].data[0].data_id:=0;
  blocks_id^[27].data[0].data_name:='Flat track going north-south (unpowered)';
  blocks_id^[27].data[1].data_id:=1;
  blocks_id^[27].data[1].data_name:='Flat track going east-west (unpowered)';
  blocks_id^[27].data[2].data_id:=2;
  blocks_id^[27].data[2].data_name:='Track ascending to the east (unpowered)';
  blocks_id^[27].data[3].data_id:=3;
  blocks_id^[27].data[3].data_name:='Track ascending to the west (unpowered)';
  blocks_id^[27].data[4].data_id:=4;
  blocks_id^[27].data[4].data_name:='Track ascending to the north (unpowered)';
  blocks_id^[27].data[5].data_id:=5;
  blocks_id^[27].data[5].data_name:='Track ascending to the south (unpowered)';
  blocks_id^[27].data[6].data_id:=8;
  blocks_id^[27].data[6].data_name:='Flat track going north-south (powered)';
  blocks_id^[27].data[7].data_id:=9;
  blocks_id^[27].data[7].data_name:='Flat track going east-west (powered)';
  blocks_id^[27].data[8].data_id:=10;
  blocks_id^[27].data[8].data_name:='Track ascending to the east (powered)';
  blocks_id^[27].data[9].data_id:=11;
  blocks_id^[27].data[9].data_name:='Track ascending to the west (powered)';
  blocks_id^[27].data[10].data_id:=12;
  blocks_id^[27].data[10].data_name:='Track ascending to the north (powered)';
  blocks_id^[27].data[11].data_id:=13;
  blocks_id^[27].data[11].data_name:='Track ascending to the south (powered)';

  blocks_id^[28].id:=28;
  blocks_id^[28].name:='Detector Rail';
  blocks_id^[28].solid:=false;
  blocks_id^[28].transparent:=true;
  blocks_id^[28].diffuse:=false;
  blocks_id^[28].light_level:=0;
  blocks_id^[28].diffuse_level:=0;
  blocks_id^[28].tile:=false;
  setlength(blocks_id^[28].data,6);
  blocks_id^[28].data[0].data_id:=0;
  blocks_id^[28].data[0].data_name:='Flat track going east-west';
  blocks_id^[28].data[1].data_id:=1;
  blocks_id^[28].data[1].data_name:='Flat track going north-south';
  blocks_id^[28].data[2].data_id:=2;
  blocks_id^[28].data[2].data_name:='Track ascending to the south';
  blocks_id^[28].data[3].data_id:=3;
  blocks_id^[28].data[3].data_name:='Track ascending to the north';
  blocks_id^[28].data[4].data_id:=4;
  blocks_id^[28].data[4].data_name:='Track ascending to the east';
  blocks_id^[28].data[5].data_id:=5;
  blocks_id^[28].data[5].data_name:='Track ascending to the west';

  blocks_id^[29].id:=29;
  blocks_id^[29].name:='Sticky Piston';
  blocks_id^[29].solid:=true;
  blocks_id^[29].transparent:=true;
  blocks_id^[29].diffuse:=false;
  blocks_id^[29].light_level:=0;
  blocks_id^[29].diffuse_level:=0;
  blocks_id^[29].tile:=false;
  setlength(blocks_id^[29].data,12);
  //todo: posmotret' podhodashie angliskie slova dla slov "vidvinut/vitanut" i "vtanut"
  blocks_id^[29].data[0].data_id:=0;
  blocks_id^[29].data[0].data_name:='Pointing down (pushed out)';
  blocks_id^[29].data[1].data_id:=1;
  blocks_id^[29].data[1].data_name:='Pointing up (pushed out)';
  blocks_id^[29].data[2].data_id:=2;
  blocks_id^[29].data[2].data_name:='Pointing east (pushed out)';
  blocks_id^[29].data[3].data_id:=3;
  blocks_id^[29].data[3].data_name:='Pointing west (pushed out)';
  blocks_id^[29].data[4].data_id:=4;
  blocks_id^[29].data[4].data_name:='Pointing north (pushed out)';
  blocks_id^[29].data[5].data_id:=5;
  blocks_id^[29].data[5].data_name:='Pointing south (pushed out)';
  blocks_id^[29].data[6].data_id:=8;
  blocks_id^[29].data[6].data_name:='Pointing down (retracted)';
  blocks_id^[29].data[7].data_id:=9;
  blocks_id^[29].data[7].data_name:='Pointing up (retracted)';
  blocks_id^[29].data[8].data_id:=10;
  blocks_id^[29].data[8].data_name:='Pointing east (retracted)';
  blocks_id^[29].data[9].data_id:=11;
  blocks_id^[29].data[9].data_name:='Pointing west (retracted)';
  blocks_id^[29].data[10].data_id:=12;
  blocks_id^[29].data[10].data_name:='Pointing north (retracted)';
  blocks_id^[29].data[11].data_id:=13;
  blocks_id^[29].data[11].data_name:='Pointing south (retracted)';

  blocks_id^[30].id:=30;
  blocks_id^[30].name:='Cobweb';
  blocks_id^[30].solid:=true;
  blocks_id^[30].transparent:=true;
  blocks_id^[30].diffuse:=false;
  blocks_id^[30].light_level:=0;
  blocks_id^[30].diffuse_level:=0;
  blocks_id^[30].tile:=false;
  setlength(blocks_id^[30].data,0);

  blocks_id^[31].id:=31;
  blocks_id^[31].name:='Tall Grass';
  blocks_id^[31].solid:=false;
  blocks_id^[31].transparent:=true;
  blocks_id^[31].diffuse:=false;
  blocks_id^[31].light_level:=0;
  blocks_id^[31].diffuse_level:=0;
  blocks_id^[31].tile:=false;
  setlength(blocks_id^[31].data,3);
  blocks_id^[31].data[0].data_id:=0;
  blocks_id^[31].data[0].data_name:='Dead shrub appearance';
  blocks_id^[31].data[1].data_id:=1;
  blocks_id^[31].data[1].data_name:='Normal tall grass';
  blocks_id^[31].data[2].data_id:=2;
  blocks_id^[31].data[2].data_name:='Fern tall grass';

  blocks_id^[32].id:=32;
  blocks_id^[32].name:='Dead Bush';
  blocks_id^[32].solid:=false;
  blocks_id^[32].transparent:=true;
  blocks_id^[32].diffuse:=false;
  blocks_id^[32].light_level:=0;
  blocks_id^[32].diffuse_level:=0;
  blocks_id^[32].tile:=false;
  setlength(blocks_id^[32].data,0);

  blocks_id^[33].id:=33;
  blocks_id^[33].name:='Piston';
  blocks_id^[33].solid:=true;
  blocks_id^[33].transparent:=true;
  blocks_id^[33].diffuse:=false;
  blocks_id^[33].light_level:=0;
  blocks_id^[33].diffuse_level:=0;
  blocks_id^[33].tile:=false;
  setlength(blocks_id^[33].data,12);
  //todo: posmotret' podhodashie angliskie slova dla slov "vidvinut/vitanut" i "vtanut"
  blocks_id^[33].data[0].data_id:=0;
  blocks_id^[33].data[0].data_name:='Pointing down (pushed out)';
  blocks_id^[33].data[1].data_id:=1;
  blocks_id^[33].data[1].data_name:='Pointing up (pushed out)';
  blocks_id^[33].data[2].data_id:=2;
  blocks_id^[33].data[2].data_name:='Pointing east (pushed out)';
  blocks_id^[33].data[3].data_id:=3;
  blocks_id^[33].data[3].data_name:='Pointing west (pushed out)';
  blocks_id^[33].data[4].data_id:=4;
  blocks_id^[33].data[4].data_name:='Pointing north (pushed out)';
  blocks_id^[33].data[5].data_id:=5;
  blocks_id^[33].data[5].data_name:='Pointing south (pushed out)';
  blocks_id^[33].data[6].data_id:=8;
  blocks_id^[33].data[6].data_name:='Pointing down (retracted)';
  blocks_id^[33].data[7].data_id:=9;
  blocks_id^[33].data[7].data_name:='Pointing up (retracted)';
  blocks_id^[33].data[8].data_id:=10;
  blocks_id^[33].data[8].data_name:='Pointing east (retracted)';
  blocks_id^[33].data[9].data_id:=11;
  blocks_id^[33].data[9].data_name:='Pointing west (retracted)';
  blocks_id^[33].data[10].data_id:=12;
  blocks_id^[33].data[10].data_name:='Pointing north (retracted)';
  blocks_id^[33].data[11].data_id:=13;
  blocks_id^[33].data[11].data_name:='Pointing south (retracted)';

  blocks_id^[34].id:=34;
  blocks_id^[34].name:='Piston Extension';
  blocks_id^[34].solid:=false;
  blocks_id^[34].transparent:=true;
  blocks_id^[34].diffuse:=false;
  blocks_id^[34].light_level:=0;
  blocks_id^[34].diffuse_level:=0;
  blocks_id^[34].tile:=false;
  setlength(blocks_id^[34].data,12);
  blocks_id^[34].data[0].data_id:=0;
  blocks_id^[34].data[0].data_name:='Pointing down (regular piston extension)';
  blocks_id^[34].data[1].data_id:=1;
  blocks_id^[34].data[1].data_name:='Pointing up (regular piston extension)';
  blocks_id^[34].data[2].data_id:=2;
  blocks_id^[34].data[2].data_name:='Pointing north(regular piston extension)';
  blocks_id^[34].data[3].data_id:=3;
  blocks_id^[34].data[3].data_name:='Pointing south(regular piston extension)';
  blocks_id^[34].data[4].data_id:=4;
  blocks_id^[34].data[4].data_name:='Pointing west (regular piston extension)';
  blocks_id^[34].data[5].data_id:=5;
  blocks_id^[34].data[5].data_name:='Pointing east (regular piston extension)';
  blocks_id^[34].data[6].data_id:=8;
  blocks_id^[34].data[6].data_name:='Pointing down (sticky piston extension)';
  blocks_id^[34].data[7].data_id:=9;
  blocks_id^[34].data[7].data_name:='Pointing up (sticky piston extension)';
  blocks_id^[34].data[8].data_id:=10;
  blocks_id^[34].data[8].data_name:='Pointing north (sticky piston extension)';
  blocks_id^[34].data[9].data_id:=11;
  blocks_id^[34].data[9].data_name:='Pointing south (sticky piston extension)';
  blocks_id^[34].data[10].data_id:=12;
  blocks_id^[34].data[10].data_name:='Pointing west (sticky piston extension)';
  blocks_id^[34].data[11].data_id:=13;
  blocks_id^[34].data[11].data_name:='Pointing east (sticky piston extension)';

  blocks_id^[35].id:=35;
  blocks_id^[35].name:='Wool';
  blocks_id^[35].solid:=true;
  blocks_id^[35].transparent:=false;
  blocks_id^[35].diffuse:=false;
  blocks_id^[35].light_level:=0;
  blocks_id^[35].diffuse_level:=0;
  blocks_id^[35].tile:=false;
  setlength(blocks_id^[35].data,16);
  blocks_id^[35].data[0].data_id:=0;
  blocks_id^[35].data[0].data_name:='White';
  blocks_id^[35].data[1].data_id:=1;
  blocks_id^[35].data[1].data_name:='Orange';
  blocks_id^[35].data[2].data_id:=2;
  blocks_id^[35].data[2].data_name:='Magneta';
  blocks_id^[35].data[3].data_id:=3;
  blocks_id^[35].data[3].data_name:='Light Blue';
  blocks_id^[35].data[4].data_id:=4;
  blocks_id^[35].data[4].data_name:='Yellow';
  blocks_id^[35].data[5].data_id:=5;
  blocks_id^[35].data[5].data_name:='Lime';
  blocks_id^[35].data[6].data_id:=6;
  blocks_id^[35].data[6].data_name:='Pink';
  blocks_id^[35].data[7].data_id:=7;
  blocks_id^[35].data[7].data_name:='Gray';
  blocks_id^[35].data[8].data_id:=8;
  blocks_id^[35].data[8].data_name:='Light Gray';
  blocks_id^[35].data[9].data_id:=9;
  blocks_id^[35].data[9].data_name:='Cyan';
  blocks_id^[35].data[10].data_id:=10;
  blocks_id^[35].data[10].data_name:='Purple';
  blocks_id^[35].data[11].data_id:=11;
  blocks_id^[35].data[11].data_name:='Blue';
  blocks_id^[35].data[12].data_id:=12;
  blocks_id^[35].data[12].data_name:='Brown';
  blocks_id^[35].data[13].data_id:=13;
  blocks_id^[35].data[13].data_name:='Green';
  blocks_id^[35].data[14].data_id:=14;
  blocks_id^[35].data[14].data_name:='Red';
  blocks_id^[35].data[15].data_id:=15;
  blocks_id^[35].data[15].data_name:='Black';

  blocks_id^[36].id:=36;
  blocks_id^[36].name:='Block moved by Piston';
  blocks_id^[36].solid:=true;
  blocks_id^[36].transparent:=false;
  blocks_id^[36].diffuse:=false;
  blocks_id^[36].light_level:=0;
  blocks_id^[36].diffuse_level:=0;
  blocks_id^[36].tile:=true;
  setlength(blocks_id^[36].data,0);

  blocks_id^[37].id:=37;
  blocks_id^[37].name:='Dandelion';
  blocks_id^[37].solid:=false;
  blocks_id^[37].transparent:=true;
  blocks_id^[37].diffuse:=false;
  blocks_id^[37].light_level:=0;
  blocks_id^[37].diffuse_level:=0;
  blocks_id^[37].tile:=false;
  setlength(blocks_id^[37].data,0);

  blocks_id^[38].id:=38;
  blocks_id^[38].name:='Rose';
  blocks_id^[38].solid:=false;
  blocks_id^[38].transparent:=true;
  blocks_id^[38].diffuse:=false;
  blocks_id^[38].light_level:=0;
  blocks_id^[38].diffuse_level:=0;
  blocks_id^[38].tile:=false;
  setlength(blocks_id^[38].data,0);

  blocks_id^[39].id:=39;
  blocks_id^[39].name:='Brown Mushroom';
  blocks_id^[39].solid:=false;
  blocks_id^[39].transparent:=true;
  blocks_id^[39].diffuse:=false;
  blocks_id^[39].light_level:=1;
  blocks_id^[39].diffuse_level:=0;
  blocks_id^[39].tile:=false;
  setlength(blocks_id^[39].data,0);

  blocks_id^[40].id:=40;
  blocks_id^[40].name:='Red Mushroom';
  blocks_id^[40].solid:=false;
  blocks_id^[40].transparent:=true;
  blocks_id^[40].diffuse:=false;
  blocks_id^[40].light_level:=0;
  blocks_id^[40].diffuse_level:=0;
  blocks_id^[40].tile:=false;
  setlength(blocks_id^[40].data,0);

  blocks_id^[41].id:=41;
  blocks_id^[41].name:='Block of Gold';
  blocks_id^[41].solid:=true;
  blocks_id^[41].transparent:=false;
  blocks_id^[41].diffuse:=false;
  blocks_id^[41].light_level:=0;
  blocks_id^[41].diffuse_level:=0;
  blocks_id^[41].tile:=false;
  setlength(blocks_id^[41].data,0);

  blocks_id^[42].id:=42;
  blocks_id^[42].name:='Block of Iron';
  blocks_id^[42].solid:=true;
  blocks_id^[42].transparent:=false;
  blocks_id^[42].diffuse:=false;
  blocks_id^[42].light_level:=0;
  blocks_id^[42].diffuse_level:=0;
  blocks_id^[42].tile:=false;
  setlength(blocks_id^[42].data,0);

  blocks_id^[43].id:=43;
  blocks_id^[43].name:='Double Slabs';
  blocks_id^[43].solid:=true;
  blocks_id^[43].transparent:=false;
  blocks_id^[43].diffuse:=false;
  blocks_id^[43].light_level:=0;
  blocks_id^[43].diffuse_level:=0;
  blocks_id^[43].tile:=false;
  setlength(blocks_id^[43].data,6);
  blocks_id^[43].data[0].data_id:=0;
  blocks_id^[43].data[0].data_name:='Stone Slabs';
  blocks_id^[43].data[1].data_id:=1;
  blocks_id^[43].data[1].data_name:='Sandstone Slabs';
  blocks_id^[43].data[2].data_id:=2;
  blocks_id^[43].data[2].data_name:='Wooden Slabs';
  blocks_id^[43].data[3].data_id:=3;
  blocks_id^[43].data[3].data_name:='Cobblestone Slabs';
  blocks_id^[43].data[4].data_id:=4;
  blocks_id^[43].data[4].data_name:='Brick Slabs';
  blocks_id^[43].data[5].data_id:=5;
  blocks_id^[43].data[5].data_name:='Stone Brick Slabs';

  blocks_id^[44].id:=44;
  blocks_id^[44].name:='Slabs';
  blocks_id^[44].solid:=false;
  blocks_id^[44].transparent:=false;
  blocks_id^[44].diffuse:=false;
  blocks_id^[44].light_level:=0;
  blocks_id^[44].diffuse_level:=0;
  blocks_id^[44].tile:=false;
  setlength(blocks_id^[44].data,0);

  blocks_id^[45].id:=45;
  blocks_id^[45].name:='Bricks';
  blocks_id^[45].solid:=true;
  blocks_id^[45].transparent:=false;
  blocks_id^[45].diffuse:=false;
  blocks_id^[45].light_level:=0;
  blocks_id^[45].diffuse_level:=0;
  blocks_id^[45].tile:=false;
  setlength(blocks_id^[45].data,0);

  blocks_id^[46].id:=46;
  blocks_id^[46].name:='TNT';
  blocks_id^[46].solid:=true;
  blocks_id^[46].transparent:=false;
  blocks_id^[46].diffuse:=false;
  blocks_id^[46].light_level:=0;
  blocks_id^[46].diffuse_level:=0;
  blocks_id^[46].tile:=false;
  setlength(blocks_id^[46].data,0);

  blocks_id^[47].id:=47;
  blocks_id^[47].name:='Bookshelf';
  blocks_id^[47].solid:=true;
  blocks_id^[47].transparent:=false;
  blocks_id^[47].diffuse:=false;
  blocks_id^[47].light_level:=0;
  blocks_id^[47].diffuse_level:=0;
  blocks_id^[47].tile:=false;
  setlength(blocks_id^[47].data,0);

  blocks_id^[48].id:=48;
  blocks_id^[48].name:='Moss Stone';
  blocks_id^[48].solid:=true;
  blocks_id^[48].transparent:=false;
  blocks_id^[48].diffuse:=false;
  blocks_id^[48].light_level:=0;
  blocks_id^[48].diffuse_level:=0;
  blocks_id^[48].tile:=false;
  setlength(blocks_id^[48].data,0);

  blocks_id^[49].id:=49;
  blocks_id^[49].name:='Obsidian';
  blocks_id^[49].solid:=true;
  blocks_id^[49].transparent:=false;
  blocks_id^[49].diffuse:=false;
  blocks_id^[49].light_level:=0;
  blocks_id^[49].diffuse_level:=0;
  blocks_id^[49].tile:=false;
  setlength(blocks_id^[49].data,0);

  blocks_id^[50].id:=50;
  blocks_id^[50].name:='Torch';
  blocks_id^[50].solid:=false;
  blocks_id^[50].transparent:=true;
  blocks_id^[50].diffuse:=false;
  blocks_id^[50].light_level:=14;
  blocks_id^[50].diffuse_level:=0;
  blocks_id^[50].tile:=false;
  setlength(blocks_id^[50].data,5);
  blocks_id^[50].data[0].data_id:=1;
  blocks_id^[50].data[0].data_name:='Pointing east';
  blocks_id^[50].data[1].data_id:=2;
  blocks_id^[50].data[1].data_name:='Pointing west';
  blocks_id^[50].data[2].data_id:=3;
  blocks_id^[50].data[2].data_name:='Pointing south';
  blocks_id^[50].data[3].data_id:=4;
  blocks_id^[50].data[3].data_name:='Pointing north';
  blocks_id^[50].data[4].data_id:=5;
  blocks_id^[50].data[4].data_name:='Standing on the floor';

  blocks_id^[51].id:=51;
  blocks_id^[51].name:='Fire';
  blocks_id^[51].solid:=false;
  blocks_id^[51].transparent:=true;
  blocks_id^[51].diffuse:=false;
  blocks_id^[51].light_level:=15;
  blocks_id^[51].diffuse_level:=0;
  blocks_id^[51].tile:=false;
  setlength(blocks_id^[51].data,0);

  blocks_id^[52].id:=52;
  blocks_id^[52].name:='Monster Spawner';
  blocks_id^[52].solid:=true;
  blocks_id^[52].transparent:=true;
  blocks_id^[52].diffuse:=false;
  blocks_id^[52].light_level:=0;
  blocks_id^[52].diffuse_level:=0;
  blocks_id^[52].tile:=true;
  setlength(blocks_id^[52].data,0);

  blocks_id^[53].id:=53;
  blocks_id^[53].name:='Wooden Stairs';
  blocks_id^[53].solid:=false;
  blocks_id^[53].transparent:=false;
  blocks_id^[53].diffuse:=false;
  blocks_id^[53].light_level:=0;
  blocks_id^[53].diffuse_level:=0;
  blocks_id^[53].tile:=false;
  setlength(blocks_id^[53].data,8);
  blocks_id^[53].data[0].data_id:=0;
  blocks_id^[53].data[0].data_name:='Ascending east';
  blocks_id^[53].data[1].data_id:=1;
  blocks_id^[53].data[1].data_name:='Ascending west';
  blocks_id^[53].data[2].data_id:=2;
  blocks_id^[53].data[2].data_name:='Ascending south';
  blocks_id^[53].data[3].data_id:=3;
  blocks_id^[53].data[3].data_name:='Ascending north';
  blocks_id^[53].data[4].data_id:=4;
  blocks_id^[53].data[4].data_name:='Ascending east (upside down)';
  blocks_id^[53].data[5].data_id:=5;
  blocks_id^[53].data[5].data_name:='Ascending west (upside down)';
  blocks_id^[53].data[6].data_id:=6;
  blocks_id^[53].data[6].data_name:='Ascending south (upside down)';
  blocks_id^[53].data[7].data_id:=7;
  blocks_id^[53].data[7].data_name:='Ascending north (upside down)';

  blocks_id^[54].id:=54;
  blocks_id^[54].name:='Chest';
  blocks_id^[54].solid:=false;
  blocks_id^[54].transparent:=true;
  blocks_id^[54].diffuse:=false;
  blocks_id^[54].light_level:=0;
  blocks_id^[54].diffuse_level:=0;
  blocks_id^[54].tile:=true;
  setlength(blocks_id^[54].data,4);
  blocks_id^[54].data[0].data_id:=2;
  blocks_id^[54].data[0].data_name:='Facing north';
  blocks_id^[54].data[1].data_id:=3;
  blocks_id^[54].data[1].data_name:='Facing south';
  blocks_id^[54].data[2].data_id:=4;
  blocks_id^[54].data[2].data_name:='Facing west';
  blocks_id^[54].data[3].data_id:=5;
  blocks_id^[54].data[3].data_name:='Facing east';

  blocks_id^[55].id:=55;
  blocks_id^[55].name:='Redstone Wire';
  blocks_id^[55].solid:=false;
  blocks_id^[55].transparent:=true;
  blocks_id^[55].diffuse:=false;
  blocks_id^[55].light_level:=0;
  blocks_id^[55].diffuse_level:=0;
  blocks_id^[55].tile:=false;
  setlength(blocks_id^[55].data,0);

  blocks_id^[56].id:=56;
  blocks_id^[56].name:='Diamond Ore';
  blocks_id^[56].solid:=true;
  blocks_id^[56].transparent:=false;
  blocks_id^[56].diffuse:=false;
  blocks_id^[56].light_level:=0;
  blocks_id^[56].diffuse_level:=0;
  blocks_id^[56].tile:=false;
  setlength(blocks_id^[56].data,0);

  blocks_id^[57].id:=57;
  blocks_id^[57].name:='Block of Diamond';
  blocks_id^[57].solid:=true;
  blocks_id^[57].transparent:=false;
  blocks_id^[57].diffuse:=false;
  blocks_id^[57].light_level:=0;
  blocks_id^[57].diffuse_level:=0;
  blocks_id^[57].tile:=false;
  setlength(blocks_id^[57].data,0);

  blocks_id^[58].id:=58;
  blocks_id^[58].name:='Crafting Table';
  blocks_id^[58].solid:=true;
  blocks_id^[58].transparent:=false;
  blocks_id^[58].diffuse:=false;
  blocks_id^[58].light_level:=0;
  blocks_id^[58].diffuse_level:=0;
  blocks_id^[58].tile:=false;
  setlength(blocks_id^[58].data,0);

  blocks_id^[59].id:=59;
  blocks_id^[59].name:='Wheat Seeds';
  blocks_id^[59].solid:=false;
  blocks_id^[59].transparent:=true;
  blocks_id^[59].diffuse:=false;
  blocks_id^[59].light_level:=0;
  blocks_id^[59].diffuse_level:=0;
  blocks_id^[59].tile:=false;
  setlength(blocks_id^[59].data,8);
  blocks_id^[59].data[0].data_id:=0;
  blocks_id^[59].data[0].data_name:='Freshly placed';
  blocks_id^[59].data[1].data_id:=1;
  blocks_id^[59].data[1].data_name:='1/7 of size';
  blocks_id^[59].data[2].data_id:=2;
  blocks_id^[59].data[2].data_name:='2/7 of size';
  blocks_id^[59].data[3].data_id:=3;
  blocks_id^[59].data[3].data_name:='3/7 of size';
  blocks_id^[59].data[4].data_id:=4;
  blocks_id^[59].data[4].data_name:='4/7 of size';
  blocks_id^[59].data[5].data_id:=5;
  blocks_id^[59].data[5].data_name:='5/7 of size';
  blocks_id^[59].data[6].data_id:=6;
  blocks_id^[59].data[6].data_name:='6/7 of size';
  blocks_id^[59].data[7].data_id:=7;
  blocks_id^[59].data[7].data_name:='Fully grown';

  blocks_id^[60].id:=60;
  blocks_id^[60].name:='Farmland';
  blocks_id^[60].solid:=false;
  blocks_id^[60].transparent:=false;
  blocks_id^[60].diffuse:=false;
  blocks_id^[60].light_level:=0;
  blocks_id^[60].diffuse_level:=0;
  blocks_id^[60].tile:=false;
  setlength(blocks_id^[60].data,0);

  blocks_id^[61].id:=61;
  blocks_id^[61].name:='Furnace';
  blocks_id^[61].solid:=true;
  blocks_id^[61].transparent:=false;
  blocks_id^[61].diffuse:=false;
  blocks_id^[61].light_level:=0;
  blocks_id^[61].diffuse_level:=0;
  blocks_id^[61].tile:=true;
  setlength(blocks_id^[61].data,4);
  blocks_id^[61].data[0].data_id:=2;
  blocks_id^[61].data[0].data_name:='Facing north';
  blocks_id^[61].data[1].data_id:=3;
  blocks_id^[61].data[1].data_name:='Facing south';
  blocks_id^[61].data[2].data_id:=4;
  blocks_id^[61].data[2].data_name:='Facing west';
  blocks_id^[61].data[3].data_id:=5;
  blocks_id^[61].data[3].data_name:='Facing east';

  blocks_id^[62].id:=62;
  blocks_id^[62].name:='Burning Furnace';
  blocks_id^[62].solid:=true;
  blocks_id^[62].transparent:=false;
  blocks_id^[62].diffuse:=false;
  blocks_id^[62].light_level:=14;
  blocks_id^[62].diffuse_level:=0;
  blocks_id^[61].tile:=true;
  setlength(blocks_id^[62].data,4);
  blocks_id^[62].data[0].data_id:=2;
  blocks_id^[62].data[0].data_name:='Facing north';
  blocks_id^[62].data[1].data_id:=3;
  blocks_id^[62].data[1].data_name:='Facing south';
  blocks_id^[62].data[2].data_id:=4;
  blocks_id^[62].data[2].data_name:='Facing west';
  blocks_id^[62].data[3].data_id:=5;
  blocks_id^[62].data[3].data_name:='Facing east';

  blocks_id^[63].id:=63;
  blocks_id^[63].name:='Sign Post';
  blocks_id^[63].solid:=false;
  blocks_id^[63].transparent:=true;
  blocks_id^[63].diffuse:=false;
  blocks_id^[63].light_level:=0;
  blocks_id^[63].diffuse_level:=0;
  blocks_id^[63].tile:=true;
  setlength(blocks_id^[63].data,16);
  blocks_id^[63].data[0].data_id:=0;
  blocks_id^[63].data[0].data_name:='Pointing south';
  blocks_id^[63].data[1].data_id:=1;
  blocks_id^[63].data[1].data_name:='Pointing south-southwest';
  blocks_id^[63].data[2].data_id:=2;
  blocks_id^[63].data[2].data_name:='Pointing southwest';
  blocks_id^[63].data[3].data_id:=3;
  blocks_id^[63].data[3].data_name:='Pointing west-southwest';
  blocks_id^[63].data[4].data_id:=4;
  blocks_id^[63].data[4].data_name:='Pointing west';
  blocks_id^[63].data[5].data_id:=5;
  blocks_id^[63].data[5].data_name:='Pointing west-northwest';
  blocks_id^[63].data[6].data_id:=6;
  blocks_id^[63].data[6].data_name:='Pointing northwest';
  blocks_id^[63].data[7].data_id:=7;
  blocks_id^[63].data[7].data_name:='Pointing north-northwest';
  blocks_id^[63].data[8].data_id:=8;
  blocks_id^[63].data[8].data_name:='Pointing north';
  blocks_id^[63].data[9].data_id:=9;
  blocks_id^[63].data[9].data_name:='Pointing north-northeast';
  blocks_id^[63].data[10].data_id:=10;
  blocks_id^[63].data[10].data_name:='Pointing northeast';
  blocks_id^[63].data[11].data_id:=11;
  blocks_id^[63].data[11].data_name:='Pointing east-northeast';
  blocks_id^[63].data[12].data_id:=12;
  blocks_id^[63].data[12].data_name:='Pointing east';
  blocks_id^[63].data[13].data_id:=13;
  blocks_id^[63].data[13].data_name:='Pointing east-southeast';
  blocks_id^[63].data[14].data_id:=14;
  blocks_id^[63].data[14].data_name:='Pointing southeast';
  blocks_id^[63].data[15].data_id:=15;
  blocks_id^[63].data[15].data_name:='Pointing south-southeast';

  blocks_id^[64].id:=64;
  blocks_id^[64].name:='Wooden Door';
  blocks_id^[64].solid:=false;
  blocks_id^[64].transparent:=true;
  blocks_id^[64].diffuse:=false;
  blocks_id^[64].light_level:=0;
  blocks_id^[64].diffuse_level:=0;
  blocks_id^[64].tile:=false;
  //todo: reshit' chto delat' s data_value
  setlength(blocks_id^[64].data,0);

  blocks_id^[65].id:=65;
  blocks_id^[65].name:='Ladders';
  blocks_id^[65].solid:=false;
  blocks_id^[65].transparent:=true;
  blocks_id^[65].diffuse:=false;
  blocks_id^[65].light_level:=0;
  blocks_id^[65].diffuse_level:=0;
  blocks_id^[65].tile:=false;
  setlength(blocks_id^[65].data,4);
  blocks_id^[65].data[0].data_id:=2;
  blocks_id^[65].data[0].data_name:='Facing north';
  blocks_id^[65].data[1].data_id:=3;
  blocks_id^[65].data[1].data_name:='Facing south';
  blocks_id^[65].data[2].data_id:=4;
  blocks_id^[65].data[2].data_name:='Facing west';
  blocks_id^[65].data[3].data_id:=5;
  blocks_id^[65].data[3].data_name:='Facing east';

  blocks_id^[66].id:=66;
  blocks_id^[66].name:='Rails';
  blocks_id^[66].solid:=false;
  blocks_id^[66].transparent:=true;
  blocks_id^[66].diffuse:=false;
  blocks_id^[66].light_level:=0;
  blocks_id^[66].diffuse_level:=0;
  blocks_id^[66].tile:=false;
  setlength(blocks_id^[66].data,10);
  blocks_id^[66].data[0].data_id:=0;
  blocks_id^[66].data[0].data_name:='Flat track going east-west';
  blocks_id^[66].data[1].data_id:=1;
  blocks_id^[66].data[1].data_name:='Flat track going north-south';
  blocks_id^[66].data[2].data_id:=2;
  blocks_id^[66].data[2].data_name:='Track ascending to the south';
  blocks_id^[66].data[3].data_id:=3;
  blocks_id^[66].data[3].data_name:='Track ascending to the north';
  blocks_id^[66].data[4].data_id:=4;
  blocks_id^[66].data[4].data_name:='Track ascending to the east';
  blocks_id^[66].data[5].data_id:=5;
  blocks_id^[66].data[5].data_name:='Track ascending to the west';
  blocks_id^[66].data[6].data_id:=6;
  blocks_id^[66].data[6].data_name:='Turn, connecting east and south';
  blocks_id^[66].data[7].data_id:=7;
  blocks_id^[66].data[7].data_name:='Turn, connecting west and south';
  blocks_id^[66].data[8].data_id:=8;
  blocks_id^[66].data[8].data_name:='Turn, connecting west and north';
  blocks_id^[66].data[9].data_id:=9;
  blocks_id^[66].data[9].data_name:='Turn, connecting east and north';

  blocks_id^[67].id:=67;
  blocks_id^[67].name:='Cobblestone Stairs';
  blocks_id^[67].solid:=false;
  blocks_id^[67].transparent:=false;
  blocks_id^[67].diffuse:=false;
  blocks_id^[67].light_level:=0;
  blocks_id^[67].diffuse_level:=0;
  blocks_id^[67].tile:=false;
  setlength(blocks_id^[67].data,8);
  blocks_id^[67].data[0].data_id:=0;
  blocks_id^[67].data[0].data_name:='Ascending east';
  blocks_id^[67].data[1].data_id:=1;
  blocks_id^[67].data[1].data_name:='Ascending west';
  blocks_id^[67].data[2].data_id:=2;
  blocks_id^[67].data[2].data_name:='Ascending south';
  blocks_id^[67].data[3].data_id:=3;
  blocks_id^[67].data[3].data_name:='Ascending north';
  blocks_id^[67].data[4].data_id:=4;
  blocks_id^[67].data[4].data_name:='Ascending east (upside down)';
  blocks_id^[67].data[5].data_id:=5;
  blocks_id^[67].data[5].data_name:='Ascending west (upside down)';
  blocks_id^[67].data[6].data_id:=6;
  blocks_id^[67].data[6].data_name:='Ascending south (upside down)';
  blocks_id^[67].data[7].data_id:=7;
  blocks_id^[67].data[7].data_name:='Ascending north (upside down)';

  blocks_id^[68].id:=68;
  blocks_id^[68].name:='Wall Sign';
  blocks_id^[68].solid:=false;
  blocks_id^[68].transparent:=true;
  blocks_id^[68].diffuse:=false;
  blocks_id^[68].light_level:=0;
  blocks_id^[68].diffuse_level:=0;
  blocks_id^[68].tile:=true;
  setlength(blocks_id^[68].data,4);
  blocks_id^[68].data[0].data_id:=2;
  blocks_id^[68].data[0].data_name:='Facing north';
  blocks_id^[68].data[1].data_id:=3;
  blocks_id^[68].data[1].data_name:='Facing south';
  blocks_id^[68].data[2].data_id:=4;
  blocks_id^[68].data[2].data_name:='Facing west';
  blocks_id^[68].data[3].data_id:=5;
  blocks_id^[68].data[3].data_name:='Facing east';

  //todo: utochnit napravlenie pri raznih data_value
  blocks_id^[69].id:=69;
  blocks_id^[69].name:='Lever';
  blocks_id^[69].solid:=false;
  blocks_id^[69].transparent:=true;
  blocks_id^[69].diffuse:=false;
  blocks_id^[69].light_level:=0;
  blocks_id^[69].diffuse_level:=0;
  blocks_id^[69].tile:=false;
  setlength(blocks_id^[69].data,6);
  blocks_id^[69].data[0].data_id:=3;
  blocks_id^[69].data[0].data_name:='Wall lever (off state)';
  blocks_id^[69].data[1].data_id:=11;
  blocks_id^[69].data[1].data_name:='Wall lever (on state)';
  blocks_id^[69].data[2].data_id:=6;
  blocks_id^[69].data[2].data_name:='Floor lever, alligned east-west (off state)';
  blocks_id^[69].data[3].data_id:=5;
  blocks_id^[69].data[3].data_name:='Floor lever, alligned north-south (off state)';
  blocks_id^[69].data[4].data_id:=14;
  blocks_id^[69].data[4].data_name:='Floor lever, alligned east-west (on state)';
  blocks_id^[69].data[5].data_id:=13;
  blocks_id^[69].data[5].data_name:='Floor lever, alligned north-south (on state)';

  blocks_id^[70].id:=70;
  blocks_id^[70].name:='Stone Pressure Plate';
  blocks_id^[70].solid:=false;
  blocks_id^[70].transparent:=true;
  blocks_id^[70].diffuse:=false;
  blocks_id^[70].light_level:=0;
  blocks_id^[70].diffuse_level:=0;
  blocks_id^[70].tile:=false;
  setlength(blocks_id^[70].data,2);
  blocks_id^[70].data[0].data_id:=0;
  blocks_id^[70].data[0].data_name:='Unpressed plate';
  blocks_id^[70].data[1].data_id:=1;
  blocks_id^[70].data[1].data_name:='Pressed plate';

  blocks_id^[71].id:=71;
  blocks_id^[71].name:='Iron Door';
  blocks_id^[71].solid:=false;
  blocks_id^[71].transparent:=true;
  blocks_id^[71].diffuse:=false;
  blocks_id^[71].light_level:=0;
  blocks_id^[71].diffuse_level:=0;
  blocks_id^[71].tile:=false;
  //todo: reshit' chto delat' s data_value
  setlength(blocks_id^[71].data,0);

  blocks_id^[72].id:=72;
  blocks_id^[72].name:='Wooden Pressure Plate';
  blocks_id^[72].solid:=false;
  blocks_id^[72].transparent:=true;
  blocks_id^[72].diffuse:=false;
  blocks_id^[72].light_level:=0;
  blocks_id^[72].diffuse_level:=0;
  blocks_id^[72].tile:=false;
  setlength(blocks_id^[72].data,2);
  blocks_id^[72].data[0].data_id:=0;
  blocks_id^[72].data[0].data_name:='Unpressed plate';
  blocks_id^[72].data[1].data_id:=1;
  blocks_id^[72].data[1].data_name:='Pressed plate';

  blocks_id^[73].id:=73;
  blocks_id^[73].name:='Redstone Ore';
  blocks_id^[73].solid:=true;
  blocks_id^[73].transparent:=false;
  blocks_id^[73].diffuse:=false;
  blocks_id^[73].light_level:=0;
  blocks_id^[73].diffuse_level:=0;
  blocks_id^[73].tile:=false;
  setlength(blocks_id^[73].data,0);

  blocks_id^[74].id:=74;
  blocks_id^[74].name:='Glowing Redstone Ore';
  blocks_id^[74].solid:=true;
  blocks_id^[74].transparent:=false;
  blocks_id^[74].diffuse:=false;
  blocks_id^[74].light_level:=9;
  blocks_id^[74].diffuse_level:=0;
  blocks_id^[74].tile:=false;
  setlength(blocks_id^[74].data,0);

  blocks_id^[75].id:=75;
  blocks_id^[75].name:='Redstone Torch (off state)';
  blocks_id^[75].solid:=false;
  blocks_id^[75].transparent:=true;
  blocks_id^[75].diffuse:=false;
  blocks_id^[75].light_level:=0;
  blocks_id^[75].diffuse_level:=0;
  blocks_id^[75].tile:=false;
  setlength(blocks_id^[75].data,0);

  blocks_id^[76].id:=76;
  blocks_id^[76].name:='Redstone Torch (on state)';
  blocks_id^[76].solid:=false;
  blocks_id^[76].transparent:=true;
  blocks_id^[76].diffuse:=false;
  blocks_id^[76].light_level:=7;
  blocks_id^[76].diffuse_level:=0;
  blocks_id^[76].tile:=false;
  setlength(blocks_id^[76].data,0);

  blocks_id^[77].id:=77;
  blocks_id^[77].name:='Stone Button';
  blocks_id^[77].solid:=false;
  blocks_id^[77].transparent:=true;
  blocks_id^[77].diffuse:=false;
  blocks_id^[77].light_level:=0;
  blocks_id^[77].diffuse_level:=0;
  blocks_id^[77].tile:=false;
  setlength(blocks_id^[77].data,8);
  blocks_id^[77].data[0].data_id:=1;
  blocks_id^[77].data[0].data_name:='Facing east (unpressed)';
  blocks_id^[77].data[1].data_id:=2;
  blocks_id^[77].data[1].data_name:='Facing west (unpressed)';
  blocks_id^[77].data[2].data_id:=3;
  blocks_id^[77].data[2].data_name:='Facing south (unpressed)';
  blocks_id^[77].data[3].data_id:=4;
  blocks_id^[77].data[3].data_name:='Facing north (unpressed)';
  blocks_id^[77].data[4].data_id:=9;
  blocks_id^[77].data[4].data_name:='Facing east (pressed)';
  blocks_id^[77].data[5].data_id:=10;
  blocks_id^[77].data[5].data_name:='Facing west (pressed)';
  blocks_id^[77].data[6].data_id:=11;
  blocks_id^[77].data[6].data_name:='Facing south (pressed)';
  blocks_id^[77].data[7].data_id:=12;
  blocks_id^[77].data[7].data_name:='Facing north (pressed)';

  blocks_id^[78].id:=78;
  blocks_id^[78].name:='Snow';
  blocks_id^[78].solid:=false;
  blocks_id^[78].transparent:=true;
  blocks_id^[78].diffuse:=false;
  blocks_id^[78].light_level:=0;
  blocks_id^[78].diffuse_level:=0;
  blocks_id^[77].tile:=false;
  setlength(blocks_id^[78].data,8);
  blocks_id^[78].data[0].data_id:=0;
  blocks_id^[78].data[0].data_name:='Normal snow height';
  blocks_id^[78].data[1].data_id:=1;
  blocks_id^[78].data[1].data_name:='2/8 of block size';
  blocks_id^[78].data[2].data_id:=2;
  blocks_id^[78].data[2].data_name:='3/8 of block size';
  blocks_id^[78].data[3].data_id:=3;
  blocks_id^[78].data[3].data_name:='4/8 of block size';
  blocks_id^[78].data[4].data_id:=4;
  blocks_id^[78].data[4].data_name:='5/8 of block size';
  blocks_id^[78].data[5].data_id:=5;
  blocks_id^[78].data[5].data_name:='6/8 of block size';
  blocks_id^[78].data[6].data_id:=6;
  blocks_id^[78].data[6].data_name:='7/8 of block size';
  blocks_id^[78].data[7].data_id:=7;
  blocks_id^[78].data[7].data_name:='Full block of snow';

  blocks_id^[79].id:=79;
  blocks_id^[79].name:='Ice';
  blocks_id^[79].solid:=true;
  blocks_id^[79].transparent:=true;
  blocks_id^[79].diffuse:=true;
  blocks_id^[79].light_level:=0;
  blocks_id^[79].diffuse_level:=2;
  blocks_id^[79].tile:=false;
  setlength(blocks_id^[79].data,0);

  blocks_id^[80].id:=80;
  blocks_id^[80].name:='Snow Block';
  blocks_id^[80].solid:=true;
  blocks_id^[80].transparent:=false;
  blocks_id^[80].diffuse:=false;
  blocks_id^[80].light_level:=0;
  blocks_id^[80].diffuse_level:=0;
  blocks_id^[80].tile:=false;
  setlength(blocks_id^[80].data,0);

  blocks_id^[81].id:=81;
  blocks_id^[81].name:='Cactus';
  blocks_id^[81].solid:=false;
  blocks_id^[81].transparent:=true;
  blocks_id^[81].diffuse:=false;
  blocks_id^[81].light_level:=0;
  blocks_id^[81].diffuse_level:=0;
  blocks_id^[81].tile:=false;
  setlength(blocks_id^[81].data,0);

  blocks_id^[82].id:=82;
  blocks_id^[82].name:='Clay Block';
  blocks_id^[82].solid:=true;
  blocks_id^[82].transparent:=false;
  blocks_id^[82].diffuse:=false;
  blocks_id^[82].light_level:=0;
  blocks_id^[82].diffuse_level:=0;
  blocks_id^[82].tile:=false;
  setlength(blocks_id^[82].data,0);

  blocks_id^[83].id:=83;
  blocks_id^[83].name:='Sugar Cane';
  blocks_id^[83].solid:=false;
  blocks_id^[83].transparent:=true;
  blocks_id^[83].diffuse:=false;
  blocks_id^[83].light_level:=0;
  blocks_id^[83].diffuse_level:=0;
  blocks_id^[83].tile:=false;
  setlength(blocks_id^[83].data,0);

  blocks_id^[84].id:=84;
  blocks_id^[84].name:='Jukebox';
  blocks_id^[84].solid:=true;
  blocks_id^[84].transparent:=false;
  blocks_id^[84].diffuse:=false;
  blocks_id^[84].light_level:=0;
  blocks_id^[84].diffuse_level:=0;
  blocks_id^[84].tile:=true;
  setlength(blocks_id^[84].data,12);
  blocks_id^[84].data[0].data_id:=0;
  blocks_id^[84].data[0].data_name:='Empty';
  blocks_id^[84].data[1].data_id:=1;
  blocks_id^[84].data[1].data_name:='Gold Disc (13)';
  blocks_id^[84].data[2].data_id:=2;
  blocks_id^[84].data[2].data_name:='Green Disc (cat)';
  blocks_id^[84].data[3].data_id:=3;
  blocks_id^[84].data[3].data_name:='Orange Disc (blocks)';
  blocks_id^[84].data[4].data_id:=4;
  blocks_id^[84].data[4].data_name:='Red Disc (chirp)';
  blocks_id^[84].data[5].data_id:=5;
  blocks_id^[84].data[5].data_name:='Lime Green Disc (far)';
  blocks_id^[84].data[6].data_id:=6;
  blocks_id^[84].data[6].data_name:='Purple Disc (mall)';
  blocks_id^[84].data[7].data_id:=7;
  blocks_id^[84].data[7].data_name:='Violet Disc (mellohi)';
  blocks_id^[84].data[8].data_id:=8;
  blocks_id^[84].data[8].data_name:='Black Disc (stal)';
  blocks_id^[84].data[9].data_id:=9;
  blocks_id^[84].data[9].data_name:='White Disc (strad)';
  blocks_id^[84].data[10].data_id:=10;
  blocks_id^[84].data[10].data_name:='Sea Green Disc (ward)';
  blocks_id^[84].data[11].data_id:=11;
  blocks_id^[84].data[11].data_name:='Broken Disc (11)';

  blocks_id^[85].id:=85;
  blocks_id^[85].name:='Fence';
  blocks_id^[85].solid:=false;
  blocks_id^[85].transparent:=true;
  blocks_id^[85].diffuse:=false;
  blocks_id^[85].light_level:=0;
  blocks_id^[85].diffuse_level:=0;
  blocks_id^[85].tile:=false;
  setlength(blocks_id^[85].data,0);

  blocks_id^[86].id:=86;
  blocks_id^[86].name:='Pumpkin';
  blocks_id^[86].solid:=true;
  blocks_id^[86].transparent:=false;
  blocks_id^[86].diffuse:=false;
  blocks_id^[86].light_level:=0;
  blocks_id^[86].diffuse_level:=0;
  blocks_id^[86].tile:=false;
  setlength(blocks_id^[86].data,4);
  blocks_id^[86].data[0].data_id:=0;
  blocks_id^[86].data[0].data_name:='Facing south';
  blocks_id^[86].data[1].data_id:=1;
  blocks_id^[86].data[1].data_name:='Facing west';
  blocks_id^[86].data[2].data_id:=2;
  blocks_id^[86].data[2].data_name:='Facing north';
  blocks_id^[86].data[3].data_id:=3;
  blocks_id^[86].data[3].data_name:='Facing east';

  blocks_id^[87].id:=87;
  blocks_id^[87].name:='Netherrack';
  blocks_id^[87].solid:=true;
  blocks_id^[87].transparent:=false;
  blocks_id^[87].diffuse:=false;
  blocks_id^[87].light_level:=0;
  blocks_id^[87].diffuse_level:=0;
  blocks_id^[87].tile:=false;
  setlength(blocks_id^[87].data,0);

  blocks_id^[88].id:=88;
  blocks_id^[88].name:='Soul Sand';
  blocks_id^[88].solid:=true;
  blocks_id^[88].transparent:=false;
  blocks_id^[88].diffuse:=false;
  blocks_id^[88].light_level:=0;
  blocks_id^[88].diffuse_level:=0;
  blocks_id^[88].tile:=false;
  setlength(blocks_id^[88].data,0);

  blocks_id^[89].id:=89;
  blocks_id^[89].name:='Glowstone Block';
  blocks_id^[89].solid:=true;
  blocks_id^[89].transparent:=false;
  blocks_id^[89].diffuse:=false;
  blocks_id^[89].light_level:=15;
  blocks_id^[89].diffuse_level:=0;
  blocks_id^[89].tile:=false;
  setlength(blocks_id^[89].data,0);

  //todo: posmotret data_value dla etogo bloka, on dolzhen bit'
  blocks_id^[90].id:=90;
  blocks_id^[90].name:='Portal';
  blocks_id^[90].solid:=false;
  blocks_id^[90].transparent:=true;
  blocks_id^[90].diffuse:=false;
  blocks_id^[90].light_level:=11;
  blocks_id^[90].diffuse_level:=0;
  blocks_id^[90].tile:=false;
  setlength(blocks_id^[90].data,0);

  blocks_id^[91].id:=91;
  blocks_id^[91].name:='Jack-O-Lantern';
  blocks_id^[91].solid:=true;
  blocks_id^[91].transparent:=false;
  blocks_id^[91].diffuse:=false;
  blocks_id^[91].light_level:=15;
  blocks_id^[91].diffuse_level:=0;
  blocks_id^[91].tile:=false;
  setlength(blocks_id^[91].data,4);
  blocks_id^[91].data[0].data_id:=0;
  blocks_id^[91].data[0].data_name:='Facing south';
  blocks_id^[91].data[1].data_id:=1;
  blocks_id^[91].data[1].data_name:='Facing west';
  blocks_id^[91].data[2].data_id:=2;
  blocks_id^[91].data[2].data_name:='Facing north';
  blocks_id^[91].data[3].data_id:=3;
  blocks_id^[91].data[3].data_name:='Facing east';

  blocks_id^[92].id:=92;
  blocks_id^[92].name:='Cake Block';
  blocks_id^[92].solid:=false;
  blocks_id^[92].transparent:=true;
  blocks_id^[92].diffuse:=false;
  blocks_id^[92].light_level:=0;
  blocks_id^[92].diffuse_level:=0;
  blocks_id^[92].tile:=false;
  setlength(blocks_id^[92].data,6);
  blocks_id^[92].data[0].data_id:=0;
  blocks_id^[92].data[0].data_name:='Full cake';
  blocks_id^[92].data[1].data_id:=1;
  blocks_id^[92].data[1].data_name:='1 piece eaten';
  blocks_id^[92].data[2].data_id:=2;
  blocks_id^[92].data[2].data_name:='2 piece eaten';
  blocks_id^[92].data[3].data_id:=3;
  blocks_id^[92].data[3].data_name:='3 piece eaten';
  blocks_id^[92].data[4].data_id:=4;
  blocks_id^[92].data[4].data_name:='4 piece eaten';
  blocks_id^[92].data[5].data_id:=5;
  blocks_id^[92].data[5].data_name:='5 piece eaten';

  blocks_id^[93].id:=93;
  blocks_id^[93].name:='Redstone Repeater (off state)';
  blocks_id^[93].solid:=false;
  blocks_id^[93].transparent:=true;
  blocks_id^[93].diffuse:=false;
  blocks_id^[93].light_level:=0;
  blocks_id^[93].diffuse_level:=0;
  blocks_id^[93].tile:=false;
  setlength(blocks_id^[93].data,16);
  blocks_id^[93].data[0].data_id:=0;
  blocks_id^[93].data[0].data_name:='Facing north (1 tick delay)';
  blocks_id^[93].data[1].data_id:=1;
  blocks_id^[93].data[1].data_name:='Facing east (1 tick delay)';
  blocks_id^[93].data[2].data_id:=2;
  blocks_id^[93].data[2].data_name:='Facing south (1 tick delay)';
  blocks_id^[93].data[3].data_id:=3;
  blocks_id^[93].data[3].data_name:='Facing west (1 tick delay)';
  blocks_id^[93].data[4].data_id:=4;
  blocks_id^[93].data[4].data_name:='Facing north (2 tick delay)';
  blocks_id^[93].data[5].data_id:=5;
  blocks_id^[93].data[5].data_name:='Facing east (2 tick delay)';
  blocks_id^[93].data[6].data_id:=6;
  blocks_id^[93].data[6].data_name:='Facing south (2 tick delay)';
  blocks_id^[93].data[7].data_id:=7;
  blocks_id^[93].data[7].data_name:='Facing west (2 tick delay)';
  blocks_id^[93].data[8].data_id:=8;
  blocks_id^[93].data[8].data_name:='Facing north (3 tick delay)';
  blocks_id^[93].data[9].data_id:=9;
  blocks_id^[93].data[9].data_name:='Facing east (3 tick delay)';
  blocks_id^[93].data[10].data_id:=10;
  blocks_id^[93].data[10].data_name:='Facing south (3 tick delay)';
  blocks_id^[93].data[11].data_id:=11;
  blocks_id^[93].data[11].data_name:='Facing west (3 tick delay)';
  blocks_id^[93].data[12].data_id:=12;
  blocks_id^[93].data[12].data_name:='Facing north (4 tick delay)';
  blocks_id^[93].data[13].data_id:=13;
  blocks_id^[93].data[13].data_name:='Facing east (4 tick delay)';
  blocks_id^[93].data[14].data_id:=14;
  blocks_id^[93].data[14].data_name:='Facing south (4 tick delay)';
  blocks_id^[93].data[15].data_id:=15;
  blocks_id^[93].data[15].data_name:='Facing west (4 tick delay)';

  blocks_id^[94].id:=94;
  blocks_id^[94].name:='Redstone Repeater (on state)';
  blocks_id^[94].solid:=false;
  blocks_id^[94].transparent:=true;
  blocks_id^[94].diffuse:=false;
  blocks_id^[94].light_level:=7;
  blocks_id^[94].diffuse_level:=0;
  blocks_id^[94].tile:=false;
  setlength(blocks_id^[94].data,16);
  blocks_id^[94].data[0].data_id:=0;
  blocks_id^[94].data[0].data_name:='Facing north (1 tick delay)';
  blocks_id^[94].data[1].data_id:=1;
  blocks_id^[94].data[1].data_name:='Facing east (1 tick delay)';
  blocks_id^[94].data[2].data_id:=2;
  blocks_id^[94].data[2].data_name:='Facing south (1 tick delay)';
  blocks_id^[94].data[3].data_id:=3;
  blocks_id^[94].data[3].data_name:='Facing west (1 tick delay)';
  blocks_id^[94].data[4].data_id:=4;
  blocks_id^[94].data[4].data_name:='Facing north (2 tick delay)';
  blocks_id^[94].data[5].data_id:=5;
  blocks_id^[94].data[5].data_name:='Facing east (2 tick delay)';
  blocks_id^[94].data[6].data_id:=6;
  blocks_id^[94].data[6].data_name:='Facing south (2 tick delay)';
  blocks_id^[94].data[7].data_id:=7;
  blocks_id^[94].data[7].data_name:='Facing west (2 tick delay)';
  blocks_id^[94].data[8].data_id:=8;
  blocks_id^[94].data[8].data_name:='Facing north (3 tick delay)';
  blocks_id^[94].data[9].data_id:=9;
  blocks_id^[94].data[9].data_name:='Facing east (3 tick delay)';
  blocks_id^[94].data[10].data_id:=10;
  blocks_id^[94].data[10].data_name:='Facing south (3 tick delay)';
  blocks_id^[94].data[11].data_id:=11;
  blocks_id^[94].data[11].data_name:='Facing west (3 tick delay)';
  blocks_id^[94].data[12].data_id:=12;
  blocks_id^[94].data[12].data_name:='Facing north (4 tick delay)';
  blocks_id^[94].data[13].data_id:=13;
  blocks_id^[94].data[13].data_name:='Facing east (4 tick delay)';
  blocks_id^[94].data[14].data_id:=14;
  blocks_id^[94].data[14].data_name:='Facing south (4 tick delay)';
  blocks_id^[94].data[15].data_id:=15;
  blocks_id^[94].data[15].data_name:='Facing west (4 tick delay)';

  blocks_id^[95].id:=95;
  blocks_id^[95].name:='Locked Chest';
  blocks_id^[95].solid:=false;
  blocks_id^[95].transparent:=true;
  blocks_id^[95].diffuse:=false;
  blocks_id^[95].light_level:=15;
  blocks_id^[95].diffuse_level:=0;
  blocks_id^[95].tile:=false;
  setlength(blocks_id^[95].data,0);

  blocks_id^[96].id:=96;
  blocks_id^[96].name:='Trapdor';
  blocks_id^[96].solid:=false;
  blocks_id^[96].transparent:=true;
  blocks_id^[96].diffuse:=false;
  blocks_id^[96].light_level:=0;
  blocks_id^[96].diffuse_level:=0;
  blocks_id^[96].tile:=false;
  setlength(blocks_id^[96].data,8);
  blocks_id^[96].data[0].data_id:=0;
  blocks_id^[96].data[0].data_name:='Attached to the south wall (closed)';
  blocks_id^[96].data[1].data_id:=1;
  blocks_id^[96].data[1].data_name:='Attached to the north wall (closed)';
  blocks_id^[96].data[2].data_id:=2;
  blocks_id^[96].data[2].data_name:='Attached to the east wall (closed)';
  blocks_id^[96].data[3].data_id:=3;
  blocks_id^[96].data[3].data_name:='Attached to the west wall (closed)';
  blocks_id^[96].data[4].data_id:=4;
  blocks_id^[96].data[4].data_name:='Attached to the south wall (opened)';
  blocks_id^[96].data[5].data_id:=5;
  blocks_id^[96].data[5].data_name:='Attached to the north wall (opened)';
  blocks_id^[96].data[6].data_id:=6;
  blocks_id^[96].data[6].data_name:='Attached to the east wall (opened)';
  blocks_id^[96].data[7].data_id:=7;
  blocks_id^[96].data[7].data_name:='Attached to the west wall (opened)';

  blocks_id^[97].id:=97;
  blocks_id^[97].name:='Hidden Silverfish';
  blocks_id^[97].solid:=true;
  blocks_id^[97].transparent:=false;
  blocks_id^[97].diffuse:=false;
  blocks_id^[97].light_level:=0;
  blocks_id^[97].diffuse_level:=0;
  blocks_id^[97].tile:=false;
  setlength(blocks_id^[97].data,3);
  blocks_id^[97].data[0].data_id:=0;
  blocks_id^[97].data[0].data_name:='Stone appearance';
  blocks_id^[97].data[1].data_id:=1;
  blocks_id^[97].data[1].data_name:='Cobblestone appearance';
  blocks_id^[97].data[2].data_id:=2;
  blocks_id^[97].data[2].data_name:='Stone Brick appearance';

  blocks_id^[98].id:=98;
  blocks_id^[98].name:='Stone Bricks';
  blocks_id^[98].solid:=true;
  blocks_id^[98].transparent:=false;
  blocks_id^[98].diffuse:=false;
  blocks_id^[98].light_level:=0;
  blocks_id^[98].diffuse_level:=0;
  blocks_id^[98].tile:=false;
  setlength(blocks_id^[98].data,4);
  blocks_id^[98].data[0].data_id:=0;
  blocks_id^[98].data[0].data_name:='Normal Brick';
  blocks_id^[98].data[1].data_id:=1;
  blocks_id^[98].data[1].data_name:='Mossy Brick';
  blocks_id^[98].data[2].data_id:=2;
  blocks_id^[98].data[2].data_name:='Cracked Brick';
  blocks_id^[98].data[3].data_id:=3;
  blocks_id^[98].data[3].data_name:='Circle Brick';

  blocks_id^[99].id:=99;
  blocks_id^[99].name:='Huge Brown Mushroom';
  blocks_id^[99].solid:=true;
  blocks_id^[99].transparent:=false;
  blocks_id^[99].diffuse:=false;
  blocks_id^[99].light_level:=0;
  blocks_id^[99].diffuse_level:=0;
  blocks_id^[99].tile:=false;
  setlength(blocks_id^[99].data,11);
  blocks_id^[99].data[0].data_id:=0;
  blocks_id^[99].data[0].data_name:='Pores on all sides';
  blocks_id^[99].data[1].data_id:=1;
  blocks_id^[99].data[1].data_name:='Cap texture on top, west and north';
  blocks_id^[99].data[2].data_id:=2;
  blocks_id^[99].data[2].data_name:='Cap texture on top and north';
  blocks_id^[99].data[3].data_id:=3;
  blocks_id^[99].data[3].data_name:='Cap texture on top, north and east';
  blocks_id^[99].data[4].data_id:=4;
  blocks_id^[99].data[4].data_name:='Cap texture on top and west';
  blocks_id^[99].data[5].data_id:=5;
  blocks_id^[99].data[5].data_name:='Cap texture on top';
  blocks_id^[99].data[6].data_id:=6;
  blocks_id^[99].data[6].data_name:='Cap texture on top and east';
  blocks_id^[99].data[7].data_id:=7;
  blocks_id^[99].data[7].data_name:='Cap texture on top, south and west';
  blocks_id^[99].data[8].data_id:=8;
  blocks_id^[99].data[8].data_name:='Cap texture on top and south';
  blocks_id^[99].data[9].data_id:=9;
  blocks_id^[99].data[9].data_name:='Cap texture on top, east and south';
  blocks_id^[99].data[10].data_id:=10;
  blocks_id^[99].data[10].data_name:='Stem on four sides, pores on top and bottom';

  blocks_id^[100].id:=100;
  blocks_id^[100].name:='Huge Red Mushroom';
  blocks_id^[100].solid:=true;
  blocks_id^[100].transparent:=false;
  blocks_id^[100].diffuse:=false;
  blocks_id^[100].light_level:=0;
  blocks_id^[100].diffuse_level:=0;
  blocks_id^[100].tile:=false;
  setlength(blocks_id^[100].data,11);
  blocks_id^[100].data[0].data_id:=0;
  blocks_id^[100].data[0].data_name:='Pores on all sides';
  blocks_id^[100].data[1].data_id:=1;
  blocks_id^[100].data[1].data_name:='Cap texture on top, west and north';
  blocks_id^[100].data[2].data_id:=2;
  blocks_id^[100].data[2].data_name:='Cap texture on top and north';
  blocks_id^[100].data[3].data_id:=3;
  blocks_id^[100].data[3].data_name:='Cap texture on top, north and east';
  blocks_id^[100].data[4].data_id:=4;
  blocks_id^[100].data[4].data_name:='Cap texture on top and west';
  blocks_id^[100].data[5].data_id:=5;
  blocks_id^[100].data[5].data_name:='Cap texture on top';
  blocks_id^[100].data[6].data_id:=6;
  blocks_id^[100].data[6].data_name:='Cap texture on top and east';
  blocks_id^[100].data[7].data_id:=7;
  blocks_id^[100].data[7].data_name:='Cap texture on top, south and west';
  blocks_id^[100].data[8].data_id:=8;
  blocks_id^[100].data[8].data_name:='Cap texture on top and south';
  blocks_id^[100].data[9].data_id:=9;
  blocks_id^[100].data[9].data_name:='Cap texture on top, east and south';
  blocks_id^[100].data[10].data_id:=10;
  blocks_id^[100].data[10].data_name:='Stem on four sides, pores on top and bottom';

  blocks_id^[101].id:=101;
  blocks_id^[101].name:='Iron Bars';
  blocks_id^[101].solid:=false;
  blocks_id^[101].transparent:=true;
  blocks_id^[101].diffuse:=false;
  blocks_id^[101].light_level:=0;
  blocks_id^[101].diffuse_level:=0;
  blocks_id^[101].tile:=false;
  setlength(blocks_id^[101].data,0);

  blocks_id^[102].id:=102;
  blocks_id^[102].name:='Glass Pane';
  blocks_id^[102].solid:=false;
  blocks_id^[102].transparent:=true;
  blocks_id^[102].diffuse:=false;
  blocks_id^[102].light_level:=0;
  blocks_id^[102].diffuse_level:=0;
  blocks_id^[102].tile:=false;
  setlength(blocks_id^[102].data,0);

  blocks_id^[103].id:=103;
  blocks_id^[103].name:='Melon';
  blocks_id^[103].solid:=true;
  blocks_id^[103].transparent:=false;
  blocks_id^[103].diffuse:=false;
  blocks_id^[103].light_level:=0;
  blocks_id^[103].diffuse_level:=0;
  blocks_id^[103].tile:=false;
  setlength(blocks_id^[103].data,0);

  blocks_id^[104].id:=104;
  blocks_id^[104].name:='Pumpkin Stem';
  blocks_id^[104].solid:=false;
  blocks_id^[104].transparent:=true;
  blocks_id^[104].diffuse:=false;
  blocks_id^[104].light_level:=0;
  blocks_id^[104].diffuse_level:=0;
  blocks_id^[104].tile:=false;
  setlength(blocks_id^[104].data,8);
  blocks_id^[104].data[0].data_id:=0;
  blocks_id^[104].data[0].data_name:='Freshly placed';
  blocks_id^[104].data[1].data_id:=1;
  blocks_id^[104].data[1].data_name:='1/7 of size';
  blocks_id^[104].data[2].data_id:=2;
  blocks_id^[104].data[2].data_name:='2/7 of size';
  blocks_id^[104].data[3].data_id:=3;
  blocks_id^[104].data[3].data_name:='3/7 of size';
  blocks_id^[104].data[4].data_id:=4;
  blocks_id^[104].data[4].data_name:='4/7 of size';
  blocks_id^[104].data[5].data_id:=5;
  blocks_id^[104].data[5].data_name:='5/7 of size';
  blocks_id^[104].data[6].data_id:=6;
  blocks_id^[104].data[6].data_name:='6/7 of size';
  blocks_id^[104].data[7].data_id:=7;
  blocks_id^[104].data[7].data_name:='Fully grown';

  blocks_id^[105].id:=105;
  blocks_id^[105].name:='Melon Stem';
  blocks_id^[105].solid:=false;
  blocks_id^[105].transparent:=true;
  blocks_id^[105].diffuse:=false;
  blocks_id^[105].light_level:=0;
  blocks_id^[105].diffuse_level:=0;
  blocks_id^[105].tile:=false;
  setlength(blocks_id^[105].data,8);
  blocks_id^[105].data[0].data_id:=0;
  blocks_id^[105].data[0].data_name:='Freshly placed';
  blocks_id^[105].data[1].data_id:=1;
  blocks_id^[105].data[1].data_name:='1/7 of size';
  blocks_id^[105].data[2].data_id:=2;
  blocks_id^[105].data[2].data_name:='2/7 of size';
  blocks_id^[105].data[3].data_id:=3;
  blocks_id^[105].data[3].data_name:='3/7 of size';
  blocks_id^[105].data[4].data_id:=4;
  blocks_id^[105].data[4].data_name:='4/7 of size';
  blocks_id^[105].data[5].data_id:=5;
  blocks_id^[105].data[5].data_name:='5/7 of size';
  blocks_id^[105].data[6].data_id:=6;
  blocks_id^[105].data[6].data_name:='6/7 of size';
  blocks_id^[105].data[7].data_id:=7;
  blocks_id^[105].data[7].data_name:='Fully grown';

  blocks_id^[106].id:=106;
  blocks_id^[106].name:='Vines';
  blocks_id^[106].solid:=false;
  blocks_id^[106].transparent:=true;
  blocks_id^[106].diffuse:=false;
  blocks_id^[106].light_level:=0;
  blocks_id^[106].diffuse_level:=0;
  blocks_id^[106].tile:=false;
  setlength(blocks_id^[106].data,16);
  blocks_id^[106].data[0].data_id:=0;
  blocks_id^[106].data[0].data_name:='Attached to top block';
  blocks_id^[106].data[1].data_id:=1;
  blocks_id^[106].data[1].data_name:='Attached to south side';
  blocks_id^[106].data[2].data_id:=2;
  blocks_id^[106].data[2].data_name:='Attached to west side';
  blocks_id^[106].data[3].data_id:=3;
  blocks_id^[106].data[3].data_name:='Attached to south and west sides';
  blocks_id^[106].data[4].data_id:=4;
  blocks_id^[106].data[4].data_name:='Attached to north side';
  blocks_id^[106].data[5].data_id:=5;
  blocks_id^[106].data[5].data_name:='Attached to north and south sides';
  blocks_id^[106].data[6].data_id:=6;
  blocks_id^[106].data[6].data_name:='Attached to north and west sides';
  blocks_id^[106].data[7].data_id:=7;
  blocks_id^[106].data[7].data_name:='Attached to north, south and west sides';
  blocks_id^[106].data[8].data_id:=8;
  blocks_id^[106].data[8].data_name:='Attached to east side';
  blocks_id^[106].data[9].data_id:=9;
  blocks_id^[106].data[9].data_name:='Attached to south and east sides';
  blocks_id^[106].data[10].data_id:=10;
  blocks_id^[106].data[10].data_name:='Attached to east and west sides';
  blocks_id^[106].data[11].data_id:=11;
  blocks_id^[106].data[11].data_name:='Attached to south, west and east sides';
  blocks_id^[106].data[12].data_id:=12;
  blocks_id^[106].data[12].data_name:='Attached to north and east sides';
  blocks_id^[106].data[13].data_id:=13;
  blocks_id^[106].data[13].data_name:='Attached to north, south and east sides';
  blocks_id^[106].data[14].data_id:=14;
  blocks_id^[106].data[14].data_name:='Attached to north, west and east sides';
  blocks_id^[106].data[15].data_id:=15;
  blocks_id^[106].data[15].data_name:='Attached to north, south, west and east sides';

  blocks_id^[107].id:=107;
  blocks_id^[107].name:='Fence Gate';
  blocks_id^[107].solid:=false;
  blocks_id^[107].transparent:=true;
  blocks_id^[107].diffuse:=false;
  blocks_id^[107].light_level:=0;
  blocks_id^[107].diffuse_level:=0;
  blocks_id^[107].tile:=false;
  setlength(blocks_id^[107].data,8);
  blocks_id^[107].data[0].data_id:=0;
  blocks_id^[107].data[0].data_name:='Facing south (closed)';
  blocks_id^[107].data[1].data_id:=1;
  blocks_id^[107].data[1].data_name:='Facing west (closed)';
  blocks_id^[107].data[2].data_id:=2;
  blocks_id^[107].data[2].data_name:='Facing north (closed)';
  blocks_id^[107].data[3].data_id:=3;
  blocks_id^[107].data[3].data_name:='Facing east (closed)';
  blocks_id^[107].data[4].data_id:=4;
  blocks_id^[107].data[4].data_name:='Facing south (opened)';
  blocks_id^[107].data[5].data_id:=5;
  blocks_id^[107].data[5].data_name:='Facing west (opened)';
  blocks_id^[107].data[6].data_id:=6;
  blocks_id^[107].data[6].data_name:='Facing north (opened)';
  blocks_id^[107].data[7].data_id:=7;
  blocks_id^[107].data[7].data_name:='Facing east (opened)';

  blocks_id^[108].id:=108;
  blocks_id^[108].name:='Brick Stairs';
  blocks_id^[108].solid:=false;
  blocks_id^[108].transparent:=false;
  blocks_id^[108].diffuse:=false;
  blocks_id^[108].light_level:=0;
  blocks_id^[108].diffuse_level:=0;
  blocks_id^[108].tile:=false;
  setlength(blocks_id^[108].data,8);
  blocks_id^[108].data[0].data_id:=0;
  blocks_id^[108].data[0].data_name:='Ascending east';
  blocks_id^[108].data[1].data_id:=1;
  blocks_id^[108].data[1].data_name:='Ascending west';
  blocks_id^[108].data[2].data_id:=2;
  blocks_id^[108].data[2].data_name:='Ascending south';
  blocks_id^[108].data[3].data_id:=3;
  blocks_id^[108].data[3].data_name:='Ascending north';
  blocks_id^[108].data[4].data_id:=4;
  blocks_id^[108].data[4].data_name:='Ascending east (upside down)';
  blocks_id^[108].data[5].data_id:=5;
  blocks_id^[108].data[5].data_name:='Ascending west (upside down)';
  blocks_id^[108].data[6].data_id:=6;
  blocks_id^[108].data[6].data_name:='Ascending south (upside down)';
  blocks_id^[108].data[7].data_id:=7;
  blocks_id^[108].data[7].data_name:='Ascending north (upside down)';

  blocks_id^[109].id:=109;
  blocks_id^[109].name:='Stone Brick Stairs';
  blocks_id^[109].solid:=false;
  blocks_id^[109].transparent:=false;
  blocks_id^[109].diffuse:=false;
  blocks_id^[109].light_level:=0;
  blocks_id^[109].diffuse_level:=0;
  blocks_id^[109].tile:=false;
  setlength(blocks_id^[109].data,8);
  blocks_id^[109].data[0].data_id:=0;
  blocks_id^[109].data[0].data_name:='Ascending east';
  blocks_id^[109].data[1].data_id:=1;
  blocks_id^[109].data[1].data_name:='Ascending west';
  blocks_id^[109].data[2].data_id:=2;
  blocks_id^[109].data[2].data_name:='Ascending south';
  blocks_id^[109].data[3].data_id:=3;
  blocks_id^[109].data[3].data_name:='Ascending north';
  blocks_id^[109].data[4].data_id:=4;
  blocks_id^[109].data[4].data_name:='Ascending east (upside down)';
  blocks_id^[109].data[5].data_id:=5;
  blocks_id^[109].data[5].data_name:='Ascending west (upside down)';
  blocks_id^[109].data[6].data_id:=6;
  blocks_id^[109].data[6].data_name:='Ascending south (upside down)';
  blocks_id^[109].data[7].data_id:=7;
  blocks_id^[109].data[7].data_name:='Ascending north (upside down)';

  blocks_id^[110].id:=110;
  blocks_id^[110].name:='Mycelium';
  blocks_id^[110].solid:=true;
  blocks_id^[110].transparent:=false;
  blocks_id^[110].diffuse:=false;
  blocks_id^[110].light_level:=0;
  blocks_id^[110].diffuse_level:=0;
  blocks_id^[110].tile:=false;
  setlength(blocks_id^[110].data,0);

  blocks_id^[111].id:=111;
  blocks_id^[111].name:='Lily Pad';
  blocks_id^[111].solid:=false;
  blocks_id^[111].transparent:=true;
  blocks_id^[111].diffuse:=false;
  blocks_id^[111].light_level:=0;
  blocks_id^[111].diffuse_level:=0;
  blocks_id^[111].tile:=false;
  setlength(blocks_id^[111].data,0);

  blocks_id^[112].id:=112;
  blocks_id^[112].name:='Nether Brick';
  blocks_id^[112].solid:=true;
  blocks_id^[112].transparent:=false;
  blocks_id^[112].diffuse:=false;
  blocks_id^[112].light_level:=0;
  blocks_id^[112].diffuse_level:=0;
  blocks_id^[112].tile:=false;
  setlength(blocks_id^[112].data,0);

  blocks_id^[113].id:=113;
  blocks_id^[113].name:='Nether Brick Fence';
  blocks_id^[113].solid:=false;
  blocks_id^[113].transparent:=true;
  blocks_id^[113].diffuse:=false;
  blocks_id^[113].light_level:=0;
  blocks_id^[113].diffuse_level:=0;
  blocks_id^[113].tile:=false;
  setlength(blocks_id^[113].data,0);

  blocks_id^[114].id:=114;
  blocks_id^[114].name:='Nether Brick Stairs';
  blocks_id^[114].solid:=false;
  blocks_id^[114].transparent:=false;
  blocks_id^[114].diffuse:=false;
  blocks_id^[114].light_level:=0;
  blocks_id^[114].diffuse_level:=0;
  blocks_id^[114].tile:=false;
  setlength(blocks_id^[114].data,8);
  blocks_id^[114].data[0].data_id:=0;
  blocks_id^[114].data[0].data_name:='Ascending east';
  blocks_id^[114].data[1].data_id:=1;
  blocks_id^[114].data[1].data_name:='Ascending west';
  blocks_id^[114].data[2].data_id:=2;
  blocks_id^[114].data[2].data_name:='Ascending south';
  blocks_id^[114].data[3].data_id:=3;
  blocks_id^[114].data[3].data_name:='Ascending north';
  blocks_id^[114].data[4].data_id:=4;
  blocks_id^[114].data[4].data_name:='Ascending east (upside down)';
  blocks_id^[114].data[5].data_id:=5;
  blocks_id^[114].data[5].data_name:='Ascending west (upside down)';
  blocks_id^[114].data[6].data_id:=6;
  blocks_id^[114].data[6].data_name:='Ascending south (upside down)';
  blocks_id^[114].data[7].data_id:=7;
  blocks_id^[114].data[7].data_name:='Ascending north (upside down)';

  blocks_id^[115].id:=115;
  blocks_id^[115].name:='Nether Wart';
  blocks_id^[115].solid:=false;
  blocks_id^[115].transparent:=true;
  blocks_id^[115].diffuse:=false;
  blocks_id^[115].light_level:=0;
  blocks_id^[115].diffuse_level:=0;
  blocks_id^[115].tile:=false;
  setlength(blocks_id^[115].data,4);
  blocks_id^[115].data[0].data_id:=0;
  blocks_id^[115].data[0].data_name:='1/3 of block';
  blocks_id^[115].data[1].data_id:=1;
  blocks_id^[115].data[1].data_name:='2/3 of block (1st stage)';
  blocks_id^[115].data[2].data_id:=2;
  blocks_id^[115].data[2].data_name:='2/3 of block (2nd stage)';
  blocks_id^[115].data[3].data_id:=3;
  blocks_id^[115].data[3].data_name:='Fully grown';

  blocks_id^[116].id:=116;
  blocks_id^[116].name:='Enchantment Table';
  blocks_id^[116].solid:=false;
  blocks_id^[116].transparent:=true;
  blocks_id^[116].diffuse:=false;
  blocks_id^[116].light_level:=0;
  blocks_id^[116].diffuse_level:=0;
  blocks_id^[116].tile:=true;
  setlength(blocks_id^[116].data,0);

  blocks_id^[117].id:=117;
  blocks_id^[117].name:='Brewing Stand';
  blocks_id^[117].solid:=false;
  blocks_id^[117].transparent:=true;
  blocks_id^[117].diffuse:=false;
  blocks_id^[117].light_level:=0;
  blocks_id^[117].diffuse_level:=0;
  blocks_id^[117].tile:=true;
  setlength(blocks_id^[117].data,8);
  blocks_id^[117].data[0].data_id:=0;
  blocks_id^[117].data[0].data_name:='Empty';
  blocks_id^[117].data[1].data_id:=1;
  blocks_id^[117].data[1].data_name:='Bottle at east slot';
  blocks_id^[117].data[2].data_id:=2;
  blocks_id^[117].data[2].data_name:='Bottle at southwest slot';
  blocks_id^[117].data[3].data_id:=3;
  blocks_id^[117].data[3].data_name:='Bottles at east and southwest slots';
  blocks_id^[117].data[4].data_id:=4;
  blocks_id^[117].data[4].data_name:='Bottle at northwest slot';
  blocks_id^[117].data[5].data_id:=5;
  blocks_id^[117].data[5].data_name:='Bottles at east and northwest slots';
  blocks_id^[117].data[6].data_id:=6;
  blocks_id^[117].data[6].data_name:='Bottles at southwest and northwest slots';
  blocks_id^[117].data[7].data_id:=7;
  blocks_id^[117].data[7].data_name:='Bottles at east, northwest and southwest slot';

  blocks_id^[118].id:=118;
  blocks_id^[118].name:='Cauldron';
  blocks_id^[118].solid:=false;
  blocks_id^[118].transparent:=true;
  blocks_id^[118].diffuse:=false;
  blocks_id^[118].light_level:=0;
  blocks_id^[118].diffuse_level:=0;
  blocks_id^[118].tile:=false;
  setlength(blocks_id^[118].data,4);
  blocks_id^[118].data[0].data_id:=0;
  blocks_id^[118].data[0].data_name:='Empty';
  blocks_id^[118].data[1].data_id:=1;
  blocks_id^[118].data[1].data_name:='1/3 filled';
  blocks_id^[118].data[2].data_id:=2;
  blocks_id^[118].data[2].data_name:='2/3 filled';
  blocks_id^[118].data[3].data_id:=3;
  blocks_id^[118].data[3].data_name:='Fully filled';

  blocks_id^[119].id:=119;
  blocks_id^[119].name:='End Portal';
  blocks_id^[119].solid:=false;
  blocks_id^[119].transparent:=true;
  blocks_id^[119].diffuse:=false;
  blocks_id^[119].light_level:=0;
  blocks_id^[119].diffuse_level:=0;
  blocks_id^[119].tile:=true;
  setlength(blocks_id^[119].data,0);

  blocks_id^[120].id:=120;
  blocks_id^[120].name:='End Portal Frame';
  blocks_id^[120].solid:=false;
  blocks_id^[120].transparent:=false;
  blocks_id^[102].diffuse:=false;
  blocks_id^[120].light_level:=0;
  blocks_id^[120].diffuse_level:=0;
  blocks_id^[120].tile:=false;
  setlength(blocks_id^[120].data,8);
  blocks_id^[120].data[0].data_id:=0;
  blocks_id^[120].data[0].data_name:='Directed south (without Eye)';
  blocks_id^[120].data[1].data_id:=1;
  blocks_id^[120].data[1].data_name:='Directed west (without Eye)';
  blocks_id^[120].data[2].data_id:=2;
  blocks_id^[120].data[2].data_name:='Directed north (without Eye)';
  blocks_id^[120].data[3].data_id:=3;
  blocks_id^[120].data[3].data_name:='Directed east (without Eye)';
  blocks_id^[120].data[4].data_id:=4;
  blocks_id^[120].data[4].data_name:='Directed south (with Eye)';
  blocks_id^[120].data[5].data_id:=5;
  blocks_id^[120].data[5].data_name:='Directed west (with Eye)';
  blocks_id^[120].data[6].data_id:=6;
  blocks_id^[120].data[6].data_name:='Directed north (with Eye)';
  blocks_id^[120].data[7].data_id:=7;
  blocks_id^[120].data[7].data_name:='Directed east (with Eye)';

  blocks_id^[121].id:=121;
  blocks_id^[121].name:='End Stone';
  blocks_id^[121].solid:=true;
  blocks_id^[121].transparent:=false;
  blocks_id^[121].diffuse:=false;
  blocks_id^[121].light_level:=0;
  blocks_id^[121].diffuse_level:=0;
  blocks_id^[121].tile:=false;
  setlength(blocks_id^[121].data,0);

  blocks_id^[122].id:=122;
  blocks_id^[122].name:='Dragon Egg';
  blocks_id^[122].solid:=false;
  blocks_id^[122].transparent:=true;
  blocks_id^[122].diffuse:=false;
  blocks_id^[122].light_level:=0;
  blocks_id^[122].diffuse_level:=0;
  blocks_id^[122].tile:=false;
  setlength(blocks_id^[122].data,0);

  blocks_id^[123].id:=123;
  blocks_id^[123].name:='Redstone Lamp (inactive)';
  blocks_id^[123].solid:=true;
  blocks_id^[123].transparent:=false;
  blocks_id^[123].diffuse:=false;
  blocks_id^[123].light_level:=0;
  blocks_id^[123].diffuse_level:=0;
  blocks_id^[123].tile:=false;
  setlength(blocks_id^[123].data,0);

  blocks_id^[124].id:=124;
  blocks_id^[124].name:='Redstone Lamp (active)';
  blocks_id^[124].solid:=true;
  blocks_id^[124].transparent:=false;
  blocks_id^[124].diffuse:=false;
  blocks_id^[124].light_level:=15;
  blocks_id^[124].diffuse_level:=0;
  blocks_id^[124].tile:=false;
  setlength(blocks_id^[124].data,0);
end;

end.
